### PR TITLE
Fix various issues found in `full_stack_target` fuzzing

### LINKED ISSUE #2804: Remove panic when inbound peer sends OpenChannelRequest with no type specified and node is manually accepting requests
This bit right here causes a panic if a correctly-formed message is sent to an LDK node that is manually accepting channel open requests:

https://github.com/lightningdevkit/rust-lightning/blob/15b7f667b05b09a25af8ab2791ea4f0752fcc2ab/lightning/src/ln/channelmanager.rs#L6184C2-L6184C2

### PR DESCRIPTION
**Pull request by TheBlueMatt**
#2804 reported a message-processing-reachable unwrap, which is concerning, but more generally it reported a serious coverage gap in our `full_stack_target` fuzzer. This fuzzer should be our first line of defense against such issues, but sadly was using a predefined config object which left us not testing cases that required specific config flags. This fixes #2804 (in an imo cleaner way than #2805, at least for downstream devs even if not in LDK) as well as a number of other quite minor debug and overflow issues found after I updated the `full_stack_target` to test different config flags.

### CODE REVIEW

File: lightning/src/ln/chan_utils.rs [hunk 1]
```diff
@@ -485,9 +485,11 @@ impl TxCreationKeys {
 }
 
 /// The maximum length of a script returned by get_revokeable_redeemscript.
-// Calculated as 6 bytes of opcodes, 1 byte push plus 2 bytes for contest_delay, and two public
-// keys of 33 bytes (+ 1 push).
-pub const REVOKEABLE_REDEEMSCRIPT_MAX_LENGTH: usize = 6 + 3 + 34*2;
+// Calculated as 6 bytes of opcodes, 1 byte push plus 3 bytes for contest_delay, and two public
+// keys of 33 bytes (+ 1 push). Generally, pushes are only 2 bytes (for values below 0x7fff, i.e.
+// around 7 months), however, a 7 month contest delay shouldn't result in being unable to reclaim
+// on-chain funds.
```
Comment (shaavan) [inline lightning/src/ln/chan_utils.rs:491]: Question:
I am not able to understand how 0x7fff corresponds to 7 months. Could you help me point to a resource that explains this? Thanks!

nit:

Since we are talking about more than a 7-month delay, which is also implied in the commit description, it makes sense to make it evident in the comment as well.

```suggestion
// keys of 33 bytes (+ 1 push). Generally, pushes are only 2 bytes (for values below 0x7fff, i.e.
// around 7 months), however, a more than 7-month contest delay shouldn't result in being unable to reclaim
// on-chain funds.
```

File: lightning/src/ln/channel.rs [hunk 2]
```diff
@@ -1876,7 +1872,8 @@ impl<SP: Deref> ChannelContext<SP> where SP::Target: SignerProvider  {
 		if let Some(feerate) = outbound_feerate_update {
```
Comment (shaavan) [inline lightning/src/ln/channel.rs:1872]: In the description above it is written:

```
// may, at any point, increase _by_ at least 10 sat/vB (i.e 2530 sat/kWU) or 25%,
// whichever is higher.
```
which implies:

```rust
cmp::max(feerate_by_kw + 2530, feerate_plus_quarter)
```

Whereas, the line should read:

```diff
pub fn get_dust_buffer_feerate(&self, outbound_feerate_update: Option<u32>) -> u32 {
                // When calculating our exposure to dust HTLCs, we assume that the channel feerate
-               // may, at any point, increase by at least 10 sat/vB (i.e 2530 sat/kWU) or 25%,
+               // may, at any point, increase to at least 10 sat/vB (i.e 2530 sat/kWU) or by 25%,
                // whichever is higher. This ensures that we aren't suddenly exposed to significantly
```

Since we are touching this function in this PR. I believe we should also address this small but significant comment change.

**Review by shaavan — COMMENTED** [review]
The changes look great! I have one small question and two suggestions for the comments.

File: lightning/src/ln/chan_utils.rs (hunk 1 above)
Comment (shaavan) [reply lightning/src/ln/chan_utils.rs:491]: Got it! Thanks for the reference @wpaulino

File: lightning/src/ln/channel.rs (hunk 2 above)
Comment (shaavan) [reply lightning/src/ln/channel.rs:1872]: Cool!

**Review by shaavan — APPROVED** [review]
ACK
The changes look great, and since the [comment](https://github.com/lightningdevkit/rust-lightning/pull/2808#discussion_r1441702317) will be addressed in a follow-up PR, I believe this PR is good to go!
