### PR TITLE
Merge initial and retry stfu send paths

### LINKED ISSUE #4429: Fuzzer hit splice-while-splice-pending debug_assert! in FundedChannel::stfu()
Repro on 62c757599b60ffae129a66ed976117dd01202198:

`echo -ne '\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xa2\xa2\xff\xa2\xa2\xa2\xa2\xff\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xa2\xff\x4c\x13' | RUSTFLAGS="--cfg=fuzzing --cfg=secp256k1_fuzz --cfg=hashes_fuzz" cargo +nightly run --features stdin_fuzz --bin chanmon_consistency_target`

Assert introduced in #4290 

```
thread 'main' (7531089) panicked at /Users/joost/repo/rust-lightning/lightning/src/ln/channel.rs:13572:7:
assertion failed: false
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/d940e56841ddcc05671ead99290e35ff2e98369f/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/d940e56841ddcc05671ead99290e35ff2e98369f/library/core/src/panicking.rs:80:14
   2: core::panicking::panic
             at /rustc/d940e56841ddcc05671ead99290e35ff2e98369f/library/core/src/panicking.rs:150:5
   3: <lightning::ln::channel::FundedChannel<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>>>::stfu::<&lightning::util::logger::WithContext<alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>>>
             at /Users/joost/repo/rust-lightning/lightning/src/ln/channel.rs:13572:7
   4: <lightning::ln::channelmanager::ChannelManager<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestChainMonitor>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestBroadcaster>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::FuzzEstimator>, &lightning_fuzz::chanmon_consistency::FuzzRouter, &lightning_fuzz::chanmon_consistency::FuzzRouter, alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>>>::internal_stfu
             at /Users/joost/repo/rust-lightning/lightning/src/ln/channelmanager.rs:12408:21
   5: <lightning::ln::channelmanager::ChannelManager<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestChainMonitor>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestBroadcaster>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::FuzzEstimator>, &lightning_fuzz::chanmon_consistency::FuzzRouter, &lightning_fuzz::chanmon_consistency::FuzzRouter, alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>> as lightning::ln::msgs::ChannelMessageHandler>::handle_stfu::{closure#0}
             at /Users/joost/repo/rust-lightning/lightning/src/ln/channelmanager.rs:15781:19
   6: <lightning::ln::channelmanager::PersistenceNotifierGuard<fn() -> lightning::ln::channelmanager::NotifyOption>>::optionally_notify::<<lightning::ln::channelmanager::ChannelManager<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestChainMonitor>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestBroadcaster>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::FuzzEstimator>, &lightning_fuzz::chanmon_consistency::FuzzRouter, &lightning_fuzz::chanmon_consistency::FuzzRouter, alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>> as lightning::ln::msgs::ChannelMessageHandler>::handle_stfu::{closure#0}, lightning::ln::channelmanager::ChannelManager<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestChainMonitor>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestBroadcaster>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::FuzzEstimator>, &lightning_fuzz::chanmon_consistency::FuzzRouter, &lightning_fuzz::chanmon_consistency::FuzzRouter, alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>>>::{closure#0}
             at /Users/joost/repo/rust-lightning/lightning/src/ln/channelmanager.rs:2964:18
   7: <lightning::ln::channelmanager::PersistenceNotifierGuard<<lightning::ln::channelmanager::PersistenceNotifierGuard<fn() -> lightning::ln::channelmanager::NotifyOption>>::optionally_notify<<lightning::ln::channelmanager::ChannelManager<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestChainMonitor>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestBroadcaster>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::FuzzEstimator>, &lightning_fuzz::chanmon_consistency::FuzzRouter, &lightning_fuzz::chanmon_consistency::FuzzRouter, alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>> as lightning::ln::msgs::ChannelMessageHandler>::handle_stfu::{closure#0}, lightning::ln::channelmanager::ChannelManager<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestChainMonitor>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestBroadcaster>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::FuzzEstimator>, &lightning_fuzz::chanmon_consistency::FuzzRouter, &lightning_fuzz::chanmon_consistency::FuzzRouter, alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>>>::{closure#0}> as core::ops::drop::Drop>::drop
             at /Users/joost/repo/rust-lightning/lightning/src/ln/channelmanager.rs:3007:9
   8: core::ptr::drop_in_place::<lightning::ln::channelmanager::PersistenceNotifierGuard<<lightning::ln::channelmanager::PersistenceNotifierGuard<fn() -> lightning::ln::channelmanager::NotifyOption>>::optionally_notify<<lightning::ln::channelmanager::ChannelManager<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestChainMonitor>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestBroadcaster>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::FuzzEstimator>, &lightning_fuzz::chanmon_consistency::FuzzRouter, &lightning_fuzz::chanmon_consistency::FuzzRouter, alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>> as lightning::ln::msgs::ChannelMessageHandler>::handle_stfu::{closure#0}, lightning::ln::channelmanager::ChannelManager<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestChainMonitor>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestBroadcaster>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::FuzzEstimator>, &lightning_fuzz::chanmon_consistency::FuzzRouter, &lightning_fuzz::chanmon_consistency::FuzzRouter, alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>>>::{closure#0}>>
             at /Users/joost/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:805:1
   9: <lightning::ln::channelmanager::ChannelManager<alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestChainMonitor>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::TestBroadcaster>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::KeyProvider>, alloc::sync::Arc<lightning_fuzz::chanmon_consistency::FuzzEstimator>, &lightning_fuzz::chanmon_consistency::FuzzRouter, &lightning_fuzz::chanmon_consistency::FuzzRouter, alloc::sync::Arc<dyn lightning::util::logger::Logger + core::marker::Sync + core::marker::Send>> as lightning::ln::msgs::ChannelMessageHandler>::handle_stfu
             at /Users/joost/repo/rust-lightning/lightning/src/ln/channelmanager.rs:15796:2
  10: lightning_fuzz::chanmon_consistency::do_test::<lightning_fuzz::utils::test_logger::DevNull>
  11: lightning_fuzz::chanmon_consistency::chanmon_consistency_test::<lightning_fuzz::utils::test_logger::DevNull>
             at ./src/chanmon_consistency.rs:2764:2
  12: chanmon_consistency_target::main::{closure#0}
             at ./src/bin/chanmon_consistency_target.rs:62:3
  13: std::panicking::catch_unwind::do_call::<chanmon_consistency_target::main::{closure#0}, ()>
             at /Users/joost/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:581:40
  14: std::panicking::catch_unwind::<(), chanmon_consistency_target::main::{closure#0}>
             at /Users/joost/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:544:19
  15: std::panic::catch_unwind::<chanmon_consistency_target::main::{closure#0}, ()>
             at /Users/joost/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
  16: chanmon_consistency_target::main
             at ./src/bin/chanmon_consistency_target.rs:61:12
  17: <fn() as core::ops::function::FnOnce<()>>::call_once
             at /Users/joost/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by wpaulino**
```
In 15b04b5, we fixed a case in `FundedChannel::try_send_stfu` where we'd
send `stfu` unnecessarily for a new splice while one is already pending.
The same case also existed in `FundedChannel::send_stfu`, but was not
fixed. There's no good reason for both of these methods to exist, so we
merge them into one as `FundedChannel::try_send_stfu`. We also add a
test that reproduces the `FundedChannel::send_stfu` issue to ensure it's
fixed and does not regress.
```

Fixes #4429.

### CODE REVIEW

File: lightning/src/ln/channel.rs [hunk 1]
```diff
@@ -13630,27 +13594,44 @@ where
...
-		//  - already quiescent
-		//  - in a state where quiescence is not possible
-		//  - not currently trying to become quiescent
-		Ok(None)
+		let initiator = if self.context.channel_state.is_remote_stfu_sent() {
+			// We may have also attempted to initiate quiescence.
+			self.context.channel_state.clear_awaiting_quiescence();
+			self.context.channel_state.clear_remote_stfu_sent();
+			self.context.channel_state.set_quiescent();
+			// We are sending an stfu in response to our couterparty's stfu, but had not yet sent
```
Comment (jkczyz) [inline lightning/src/ln/channel.rs]: s/couterparty/counterparty

File: lightning/src/ln/channel.rs [hunk 2]
```diff
@@ -749,13 +748,8 @@ define_state_flags!(
...
 			AWAITING_REMOTE_REVOKE, state_flags::AWAITING_REMOTE_REVOKE,
 			is_awaiting_remote_revoke, set_awaiting_remote_revoke, clear_awaiting_remote_revoke),
-		("Indicates a local request has been made for the channel to become quiescent. Both nodes \
-			must send `stfu` for the channel to become quiescent. This flag will be cleared and we \
-			will no longer attempt quiescence if either node requests a shutdown.",
-			AWAITING_QUIESCENCE, state_flags::AWAITING_QUIESCENCE,
-			is_awaiting_quiescence, set_awaiting_quiescence, clear_awaiting_quiescence),
 		("Indicates we have sent a `stfu` message to the counterparty. This message can only be sent \
-			if either `AWAITING_QUIESCENCE` or `REMOTE_STFU_SENT` is set. Shutdown requests are \
+			if `REMOTE_STFU_SENT` is set, or a `QuiscentAction` is pending. Shutdown requests are \
```
Comment (jkczyz) [inline lightning/src/ln/channel.rs]: s/QuiscentAction/QuiescentAction

File: lightning/src/ln/channel.rs [hunk 3]
```diff
@@ -10747,11 +10729,6 @@ where
 		// From here on out, we may not fail!
 
 		self.context.channel_state.set_remote_shutdown_sent();
-		if self.context.channel_state.is_awaiting_quiescence() {
-			// We haven't been able to send `stfu` yet, and there's no point in attempting
-			// quiescence anymore since the counterparty wishes to close the channel.
-			self.context.channel_state.clear_awaiting_quiescence();
-		}
```
Comment (jkczyz) [inline lightning/src/ln/channel.rs:10754]: If we have a `QuiescenAction` set, will we keep trying to send `stfu`?

File: lightning/src/ln/channel.rs [hunk 4]
```diff
@@ -11526,17 +11503,6 @@ where
 		let announcement_sigs =
 			self.get_announcement_sigs(node_signer, chain_hash, user_config, block_height, logger);
 
-		if let Some(quiescent_action) = self.quiescent_action.as_ref() {
-			// TODO(splicing): If we didn't win quiescence, then we can contribute as an acceptor
-			// instead of waiting for the splice to lock.
```
Comment (jkczyz) [inline lightning/src/ln/channel.rs:11531]: Probably no need to worry since this is handled in #4416, but looks like this TODO wasn't moved.

File: lightning/src/ln/channel.rs [hunk 5]
```diff
@@ -13570,13 +13531,11 @@ where
...
-		if self.context.channel_state.is_local_stfu_sent()
-			|| self.context.channel_state.is_quiescent()
-		{
+		if self.quiescent_action.is_none() && !self.context.channel_state.is_remote_stfu_sent() {
 			return None;
 		}
-		if !self.context.channel_state.is_awaiting_quiescence()
-			&& !self.context.channel_state.is_remote_stfu_sent()
+		if self.context.channel_state.is_local_stfu_sent()
+			|| self.context.channel_state.is_quiescent()
```
Comment (jkczyz) [inline lightning/src/ln/channel.rs]: nit: diff would be cleaner if the order of the `if` blocks wasn't flipped.

Comment (wpaulino) [reply lightning/src/ln/channel.rs]: It was intentional. Logically, you'd first want to check what states you're expected to send `stfu` in.

File: lightning/src/ln/channel.rs (hunk 3 above)
Comment (wpaulino) [reply lightning/src/ln/channel.rs:10754]: We shouldn't, added a commit to fix this. I thought it was already done, but we only did it in `force_shutdown`.
