### PR TITLE
Ignore RGS channel updates for unknown channels

### LINKED ISSUE #1784: RGS Fails When Channel Was Removed
If we remove a channel, for example because we got a failed payment with an error which told us to, we'll hit the following block, which shouldn't actually be an error, we should simply ignore this and move on. Fixing this is somewhat nontrivial as we still have to read the relevant data, we just have to ignore it, so it will require a bit of code motion.

```
                    .ok_or(LightningError {
                        err: "Couldn't find channel for update".to_owned(),
                        action: ErrorAction::IgnoreError,
                    })?;
```

### PR DESCRIPTION
**Pull request by johncantrell97**
Fixes #1784 by ignoring channel updates for channels our graph doesn't know about instead of returning an error.  Also includes a minor style change with added test for unknown version header.  I can remove that part but was just something I noticed when first reviewing RGS client code.  Maybe there's a reason it was using the empty match arm style that I'm unaware of?

### CODE REVIEW

File: lightning-rapid-gossip-sync/src/processing.rs [hunk 1]
```diff
@@ -75,6 +72,8 @@ impl<NG: Deref<Target=NetworkGraph<L>>, L: Deref> RapidGossipSync<NG, L> where L
 
 			let node_id_1_index: BigSize = Readable::read(read_cursor)?;
 			let node_id_2_index: BigSize = Readable::read(read_cursor)?;
+
+			// Is this only because we truncate max node ids read? Why not do a >0 bounds check as well :shrug:
```
Comment (arik-so) [inline lightning-rapid-gossip-sync/src/processing.rs:76]: it preëmpts an array index out of bounds error. >=0 is unnecessary because bigsize only supports unsigned ints under the hood

**Review by arik-so — DISMISSED** [review]
This is quite elegant. But please remove the comment in line 76.

File: lightning-rapid-gossip-sync/src/processing.rs (hunk 1 above)
Comment (johncantrell97) [reply lightning-rapid-gossip-sync/src/processing.rs]: got it, makes sense on the bigsize -- thanks

**Comment by johncantrell97** [comment]
> This is quite elegant. But please remove the comment in line 76.

Thanks, just force pushed without the comment.

**Review by arik-so — APPROVED** [review]
