### PR TITLE
Skip any erroring entry in `FilesystemStore::list`

### LINKED ISSUE #3795: `FilesystemStore::list` is not safe to call concurrently
We can have a file/dir removed between `fs::read_dir` and `dir_entry_is_key` looks at its metadata which causes a spurious error. Obviously `list` will always return a set that may be bogus by the time its used, but that should be pretty clear from the API, the call shouldn't fail, however (and its probably okay that its internally-inconsistent).

### PR DESCRIPTION
**Pull request by tnull**
Closes #3795.

Previously, we would bubble up any error that we'd encouter during retrieving the metadata for all listed entries. Here we relax this somewhat to allow for minor inconsistencies between reading the directory entries and checking whether they are valid key entries.

### CODE REVIEW

**Comment by tnull** [comment]
> What do we want to do about `MigratableKVStore::list_all_keys`?

I don't think we should change anything about that, as for migration we'd want be as strict as possible? For one, users really shouldn't run migration in-parallel to anything else (which is basically already documented on `migrate_kv_store_data`), and *if* we hit some inconsistencies the user probably needs to take a look rather than the migration just silently continuing with some items missing.

> I also feel like we need to specify the expected semantics at the API-level here. This change can allow for an inconsistent list view - eg if someone wrote key A then deleted key B the list API can return a value without A and without B, which is weird in some cases.

Are we sure this would be the case? I'm not sure if it is honestly. Before we change the docs, we should probably first try to understand better what exactly happened in the user-reported instance.

**Comment by TheBlueMatt** [comment]
> Are we sure this would be the case? I'm not sure if it is honestly. Before we change the docs, we should probably first try to understand better what exactly happened in the user-reported instance.

I think so. We'd first list the directory entries that doesn't have A or B, then the other thread can remove A and write B and the loop will go through, detect that A is missing and ignore it, but never look for B. Absent a full restart of the whole loop and giving up after a while I'm not sure how we'd fix it, though, honestly.

**Comment by tnull** [comment]
> I think so. We'd first list the directory entries that doesn't have A or B, then the other thread can remove A and write B and the loop will go through, detect that A is missing and ignore it, but never look for B. Absent a full restart of the whole loop and giving up after a while I'm not sure how we'd fix it, though, honestly.

Issues like this reminds me that we still need to provide a better default `KVStore` implementation and discourage `FilesystemStore` for production use, IMO.

**Comment by tnull** [comment]
> I also feel like we need to specify the expected semantics at the API-level here. This change can allow for an inconsistent list view - eg if someone wrote key A then deleted key B the list API can return a value without A and without B, which is weird in some cases.

Coming back to this: I don't think we'd want to change any `KVStore` specifications just because of an implementation detail of `FilesystemStore`. Where would you expect the specifics to be documented then? The trait implementation on `FilesystemStore`, even though this might not be super discoverable?

**Comment by TheBlueMatt** [comment]
> Issues like this reminds me that we still need to provide a better default KVStore implementation and discourage FilesystemStore for production use, IMO.

The same issue applies in any KVStore once we're looking at multi-level issues.

**Comment by tnull** [comment]
> Actually, we should be able to fix this by calling https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.file_type instead.

How come? IIUC, `DirEntry::file_type` is very often just a shortcut for calling `DirEntry::metadata::file_type`:

https://github.com/rust-lang/rust/blob/68ac5abb067806a88464ddbfbd3c7eec877b488d/library/std/src/sys/fs/unix.rs#L945-L969

So why would this reliably solve the issue at hand?

**Comment by TheBlueMatt** [comment]
Currently the code calls `DirEntry::path()` and then calls `metadata` on that `Path`, doing a syscall to fetch the metadata. We actually can call `DirEntry::metadata()` which avoids the syscall and will tell us what the file type was when the `list` operation happened, avoiding the race. It looks like `file_type` may also reduce the race further on some platforms, but, indeed, not on common ones.

**Comment by tnull** [comment]
> Currently the code calls `DirEntry::path()` and then calls `metadata` on that `Path`, doing a syscall to fetch the metadata. We actually can call `DirEntry::metadata()` which avoids the syscall and will tell us what the file type was when the `list` operation happened, avoiding the race. It looks like `file_type` may also reduce the race further on some platforms, but, indeed, not on common ones.

Not sure if I follow here. Now pushed a fixup using `DirEntry::metadata`, but AFAICT, this still calls back into `statx`/`fstatat64` (see https://github.com/rust-lang/rust/blob/68ac5abb067806a88464ddbfbd3c7eec877b488d/library/std/src/sys/fs/unix.rs#L918), so how is this not a syscall, and how is it not race-y?

**Comment by TheBlueMatt** [comment]
Oh, hmm, my memory was fuzzy on what `readdir` included. Nevermind, but we should use `file_type` directly. While it'll still be race-y on "solaris", "illumos", "haiku", "vxworks", "aix", "nto", "vita", and "some filesystems" (per `readdir(3)`), I don't even recognize a few of those and am pretty confident we'll never have users on most of them :).

Sadly, per `readdir(3)`, it looks like we still need to handle the race better somehow, as "Currently,  only  some filesystems (among them: Btrfs, ext2, ext3, and ext4) have full support for returning the file type in d_type.  All applications must properly handle a return of DT_UNKNOWN." Really we should have been naming the directories different from files, is it still too late to do that?

**Comment by TheBlueMatt** [comment]
Also, actually, `list`'s docs are ambiguous to begin with. It says only "Returns a list of keys that are stored under the given `secondary_namespace` in `primary_namespace`." Why is it skipping directories to begin with?

**Comment by tnull** [comment]
> Why is it skipping directories to begin with?

Because “directories” are a concept that is only known to the specific implementation that is `FilesystemStore`, which we decidedly didn’t include/mention in the API when we went with ‘namespaces’.

**Comment by TheBlueMatt** [comment]
Right, but generally they indicate the presence of a sub-namespace. Which presumably we *should* return per the docs on `list`, afaict?

**Comment by tnull** [comment]
> Right, but generally they indicate the presence of a sub-namespace. Which presumably we _should_ return per the docs on `list`, afaict?

No, we discussed this several times in the past, and IIRC we can't just require that a) due to how our upgrade path from the original `KVStorePersister` looked like, but also b) since we so far don't require it and we don't know how exactly our users use these namespaces. For example, in VSS we don't have the notion of namespaces really, but simply build a single key that is `primary_namespace#secondary_namespace#obfuscated_key` and we list by [`key_prefix`](https://docs.rs/vss-client/latest/vss_client/types/struct.ListKeyVersionsRequest.html#structfield.key_prefix). If we'd suddenly require to return all sub-/namespaces also, we'd need to always list all keys and manually extract (hopefully also deobfuscate, once we do obfuscate) them, which would be very costly.

So, TLDR: yes, would have been great, but we didn't/couldn't do it this way, which is also why we had to introduce a separate `list_all_keys` method in `MigratableKVStore` (as otherwise we could have iteratively explored the entire keyspace based on the returned sub-/namespaces).

>  Really we should have been naming the directories different from files, is it still too late to do that?

See above: directories are a filesystem-only concept. And yes, technically we do name them differently in that we don't return them at all, which we can't easily change without breaking backwards compatibility.^^

**Comment by TheBlueMatt** [comment]
> For example, in VSS we don't have the notion of namespaces really, but simply build a single key that is primary_namespace#secondary_namespace#obfuscated_key and we list by [key_prefix](https://docs.rs/vss-client/latest/vss_client/types/struct.ListKeyVersionsRequest.html#structfield.key_prefix).

I'm confused, a key prefix should allow for listing sub-namespaces.

**Comment by tnull** [comment]
> I'm confused, a key prefix should allow for listing sub-namespaces.

No? It would list all keys under the given prefix? So when we try to discover namespaces/sub-namespaces we'd list all keys in the store, and *then* filter down the results, every time?

**Comment by tnull** [comment]
@TheBlueMatt Any further comments here? I'm still not sure what the conclusion is here (short of eventually deprecating `FilesystemStore`).

**Comment by TheBlueMatt** [comment]
I guess I'm still kinda confused. The docs for `list` say only:

"Returns a list of keys that are stored under the given `secondary_namespace` in `primary_namespace`."

This implies to me that it can only be used to list the last-level keys, ie we should never encounter any sub-namespaces in a `list` at all. This matches how its used in `lightning`, as well, though it could be used differently elsewhere. It also implies that we can simply remove the `dir_entry_is_key` check entirely as we should never find a directory at all (though we could fail if we do find one, of course).

**Comment by tnull** [comment]
> This implies to me that it can only be used to list the last-level keys, ie we should never encounter any sub-namespaces in a `list` at all.

Not exactly, as we allow for empty primary and secondary namespaces *or* an empty secondary namespace:

```
Empty primary namespaces and secondary namespaces ("") are assumed to be a valid, however, if primary_namespace is empty, secondary_namespace is required to be empty, too. 
```

> It also implies that we can simply remove the `dir_entry_is_key` check entirely as we should never find a directory at all (though we could fail if we do find one, of course).

Well, no, as we still need to be able to handle the empty namespaces, e.g., `//manager`, etc. So we *do* need to be able to list entries on higher levels, but just if they qualify as keys.

**Comment by TheBlueMatt** [comment]
Ah, duh, right, sorry. Really a shame we didn't put the top-level entries under a different key. Switching to the iterator metadata approach should fix this for common cases, I guess, but I wonder if we shouldn't put a top-level loop in `list` at least for cases where we get specifically the doesnt-exist error?

**Comment by tnull** [comment]
> Ah, duh, right, sorry. Really a shame we didn't put the top-level entries under a different key. Switching to the iterator metadata approach should fix this for common cases, I guess, but I wonder if we shouldn't put a top-level loop in `list` at least for cases where we get specifically the doesnt-exist error?

I now squashed the fixup and rewrote the commit message here. Not the biggest fan of adding a loop there as it might be unexpected for users that we just retry in this particular case.

**Comment by tnull** [comment]
> Not sure how we can fix this issue without either (a) looping until we succeed or (b) changing the `KVStore` API so that we're allowed to return partial results in case of "tears" here. 

It really shows the that using the filesystem simply has some shortcomings and doesn't provide basic ACID guarantees, especially across different platforms. In my eyes neither a) nor b) is an option:

a) if we'd add a loop, we def. can't loop forever. So we'll have to add proper retry logic on our end, aborting operation after N retries. But, any magic number N here could lead to behavior that the user doesn't expect, especially if the API contract is that we bubble up IO errors. We'd need to make N configurable and document it, which is in turn an impossible API since no user will really understand what this parameter is for.

b) I don't think this is a good option either. `KVStore` has nothing to do with `FilesystemStore`, i.e., you can't just relax the API guarantees at the interface level after the fact here, just to address the shortcomings of a single implementation. FWIW, we're about to add a bunch of additional requirements for the async variant of `KVStore`, and given what we learnt about this issue here, I doubt a wrapped `FilesystemStore` will really hold up over time.

IMO we fixed what was immediately addressable in this PR, but the real fix will be to add fully-supported SQLite/Postgres backends to `rust-lightning`, and advise users to migrate to a proper database backend.

> The current PR fixes the logic for ext4/btrfs, but not every FS, and eg I doubt it fixes it for c=.

They already implement retry logic around the `FilesystemStore` on their end, they just need to stop panicking on any error. (cc @domZippilli)

**Comment by domZippilli** [comment]
Thanks for the ping.

> the real fix will be to add fully-supported SQLite/Postgres backends to rust-lightning

If I get the time and mandate, something like this would be fun to write. Now that you all use rustfmt, I bet it wouldn't even get 500 comments.

**Comment by TheBlueMatt** [comment]
> It really shows the that using the filesystem simply has some shortcomings and doesn't provide basic ACID guarantees, especially across different platforms.

This isn't true. We screwed up the directory structure and are hitting this issue because of it. If we put top-level keys in a directory instead we'd be just fine here. Plenty of large applications use filesystems as K-V stores and they generally are really good at it!

> a) if we'd add a loop, we def. can't loop forever. So we'll have to add proper retry logic on our end, aborting operation after N retries. But, any magic number N here could lead to behavior that the user doesn't expect, especially if the API contract is that we bubble up IO errors.

Given we've hit this only recently in prod even with a large node that does high-latency persistence, I imagine a few loops will ~always work in practice unless there's something really bad going on. Indeed, we might want a limit, but that limit can be fairly high and I don't think we need to worry about that too much.

> We'd need to make N configurable and document it, which is in turn an impossible API since no user will really understand what this parameter is for.

Or not?

> b) I don't think this is a good option either. KVStore has nothing to do with FilesystemStore, i.e., you can't just relax the API guarantees at the interface level after the fact here, just to address the shortcomings of a single implementation.

I tend to agree. Hence why we should add a loop :)

> FWIW, we're about to add a bunch of additional requirements for the async variant of KVStore, and given what we learnt about this issue here, I doubt a wrapped FilesystemStore will really hold up over time.

This is news to me? What requirements are we adding and why would they be problematic here?

> They already implement retry logic around the FilesystemStore on their end, they just need to stop panicking on any error. (cc @domZippilli)

Which probably means we really need to take that logic upstream and add a loop?

**Comment by tnull** [comment]
As mentioned elsewhere, I still think retry logic  shouldn't necessarily be the concern of `FilesystemStore`, but I'll now concede as it's also not a super strongly held opinion. So now went ahead and added a `loop` / `retry` logic in `FilesystemStore::list`.

File: lightning-persister/src/fs_store.rs [hunk 1]
```diff
@@ -377,7 +378,7 @@ fn dir_entry_is_key(p: &Path) -> Result<bool, lightning::io::Error> {
 	Ok(true)
 }
 
-fn get_key_from_dir_entry(p: &Path, base_path: &Path) -> Result<String, lightning::io::Error> {
+fn git_key_from_dir_entry_path(p: &Path, base_path: &Path) -> Result<String, lightning::io::Error> {
```
Comment (TheBlueMatt) [inline lightning-persister/src/fs_store.rs]: git :joy:

File: lightning-persister/src/fs_store.rs [hunk 2]
```diff
@@ -33,6 +33,10 @@ fn path_to_windows_str<T: AsRef<OsStr>>(path: &T) -> Vec<u16> {
 // The number of read/write/remove/list operations after which we clean up our `locks` HashMap.
 const GC_LOCK_INTERVAL: usize = 25;
 
+// The number of times we retry listing keys in `FilesystemStore::list` before we give up reaching
+// a consistent view and error out.
+const LIST_DIR_CONSISTENCY_RETRIES: usize = 3;
```
Comment (TheBlueMatt) [inline lightning-persister/src/fs_store.rs]: Why not 10? 3 is not a very high number and ideally we want to be able to delay until some monitor update cleanup process finishes.

File: lightning-persister/src/fs_store.rs (hunk 1 above)
Comment (tnull) [reply lightning-persister/src/fs_store.rs]: :sob: will fix.

File: lightning-persister/src/fs_store.rs (hunk 2 above)
Comment (tnull) [reply lightning-persister/src/fs_store.rs]: > ideally we want to be able to delay

Well, that is yet another reason why I dislike doing it here rather than leaving it to the user: we have no way to implement back-off / sleeping in this code here. Anyways, will switch to 10 if you prefer.

**Comment by tnull** [comment]
Amended with the following changes:
```diff
diff --git a/lightning-persister/src/fs_store.rs b/lightning-persister/src/fs_store.rs
index 735b68165..5580382b3 100644
--- a/lightning-persister/src/fs_store.rs
+++ b/lightning-persister/src/fs_store.rs
@@ -36,5 +36,5 @@ const GC_LOCK_INTERVAL: usize = 25;
 // The number of times we retry listing keys in `FilesystemStore::list` before we give up reaching
 // a consistent view and error out.
-const LIST_DIR_CONSISTENCY_RETRIES: usize = 3;
+const LIST_DIR_CONSISTENCY_RETRIES: usize = 10;

 /// A [`KVStoreSync`] implementation that writes to and reads from the file system.
@@ -328,5 +328,5 @@ impl KVStoreSync for FilesystemStore {
                                match res {
                                        Ok(true) => {
-                                               let key = git_key_from_dir_entry_path(&p, &prefixed_dest)?;
+                                               let key = get_key_from_dir_entry_path(&p, &prefixed_dest)?;
                                                keys.push(key);
                                        },
@@ -405,5 +405,5 @@ fn dir_entry_is_key(dir_entry: &fs::DirEntry) -> Result<bool, lightning::io::Err
 }

-fn git_key_from_dir_entry_path(p: &Path, base_path: &Path) -> Result<String, lightning::io::Error> {
+fn get_key_from_dir_entry_path(p: &Path, base_path: &Path) -> Result<String, lightning::io::Error> {
        match p.strip_prefix(&base_path) {
                Ok(stripped_path) => {
@@ -469,5 +469,5 @@ impl MigratableKVStore for FilesystemStore {
                                let primary_namespace = String::new();
                                let secondary_namespace = String::new();
-                               let key = git_key_from_dir_entry_path(&primary_path, prefixed_dest)?;
+                               let key = get_key_from_dir_entry_path(&primary_path, prefixed_dest)?;
                                keys.push((primary_namespace, secondary_namespace, key));
                                continue 'primary_loop;
@@ -481,7 +481,7 @@ impl MigratableKVStore for FilesystemStore {
                                if dir_entry_is_key(&secondary_entry)? {
                                        let primary_namespace =
-                                               git_key_from_dir_entry_path(&primary_path, prefixed_dest)?;
+                                               get_key_from_dir_entry_path(&primary_path, prefixed_dest)?;
                                        let secondary_namespace = String::new();
-                                       let key = git_key_from_dir_entry_path(&secondary_path, &primary_path)?;
+                                       let key = get_key_from_dir_entry_path(&secondary_path, &primary_path)?;
                                        keys.push((primary_namespace, secondary_namespace, key));
                                        continue 'secondary_loop;
@@ -495,8 +495,8 @@ impl MigratableKVStore for FilesystemStore {
                                        if dir_entry_is_key(&tertiary_entry)? {
                                                let primary_namespace =
-                                                       git_key_from_dir_entry_path(&primary_path, prefixed_dest)?;
+                                                       get_key_from_dir_entry_path(&primary_path, prefixed_dest)?;
                                                let secondary_namespace =
-                                                       git_key_from_dir_entry_path(&secondary_path, &primary_path)?;
-                                               let key = git_key_from_dir_entry_path(&tertiary_path, &secondary_path)?;
+                                                       get_key_from_dir_entry_path(&secondary_path, &primary_path)?;
+                                               let key = get_key_from_dir_entry_path(&tertiary_path, &secondary_path)?;
                                                keys.push((primary_namespace, secondary_namespace, key));
                                        } else {
```

File: lightning-persister/src/fs_store.rs [hunk 3]
```diff
@@ -306,23 +310,45 @@ impl KVStoreSync for FilesystemStore {
...
+						let key = get_key_from_dir_entry_path(&p, &prefixed_dest)?;
+						keys.push(key);
+					},
+					Ok(false) => {
+						// We didn't error, but the entry is not a valid key (e.g., a directory,
+						// or a temp file).
+						continue 'skip_entry;
+					},
+					Err(e) => {
+						if e.kind() == lightning::io::ErrorKind::NotFound && retries > 0 {
```
Comment (TheBlueMatt) [inline lightning-persister/src/fs_store.rs:339]: I don't think this is right because the `dir_entry_is_key` `metadata()` call gets its error mapped to an `ErrorKind::Other`.

Comment (tnull) [reply lightning-persister/src/fs_store.rs:339]: Ah, good catch, I had forgotten we started to do that at some point. Now added a commit reverting this, as remapping to `ErrorKind::Other` is nonsense, IMO, if we already have stronger typed `io::Error`.
