### PR TITLE
Upstream and fix preflight probing

### LINKED ISSUE #2499: Add heuristic to LDK code or docs
From LDK Discord, @TheBlueMatt:

"Because there’s rarely liquidity limits for reasonable-value payments in the “core” of  ln, one trivial heuristic would be to decline to send a pre-flight probe if the amount is > 1/3 of your available outbound liquidity on a channel that’s used for the probe"

"presumably ldk-node should do that for you, but we may want to document these guidelines in rust-lightning too
or have a wrapper which does the checks pre-flight in ChannelManager"

### LINKED ISSUE #2517: Probe only up to the last public hop if there's no other choices
If we're doing pre-flight probing for a payment, and the last hop is from an invoice route hint, and there's only one option for the last-hop route, and the node is not public, there's no reason to probe through to the endpoint - we might as well probe to the second-to-last hop. Worse, probing to the endpoint may confuse some LSPs, causing them to open a JIT channel when there's no real payment yet. For ldk-node this should be ~easy, for LDK itself we probably want to do it as a part of #2499.

cc @tnull

### LINKED ISSUE #2525: Unable to `send_probe` to eclair due to lack of payment secret
Because of this issue, eclair requires payment secret when sending probes: https://github.com/ACINQ/eclair/pull/1810#issuecomment-904479387

Right now I'm getting: 

```
INFO  [lightning::ln::onion_utils:579] Onion Error[from 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f: invalid_onion_payload(0x4016)] Node indicated that the decrypted onion per-hop payload was not understood by it or is incomplete
```

And I think it's because when sending probes, it uses `sponaneous_empty` which does not send payment secret.

https://github.com/lightningdevkit/rust-lightning/blob/3dffe54258a374d15571d4ec72f5faa02477b770/lightning/src/ln/outbound_payment.rs#L984-L993

https://github.com/lightningdevkit/rust-lightning/blob/3dffe54258a374d15571d4ec72f5faa02477b770/lightning/src/ln/outbound_payment.rs#L461-L463

Would always sending payment secret be the right approach? Don't all nodes support it at this point? Or would allowing `send_probe` to pass through `RecipientOnionFields` be a work around and I can hardcode their node pubkey for it.

### PR DESCRIPTION
**Pull request by tnull**
Fixes #2525.
Closes #2499.
Closes #2517.

Currently still WIP and hence in draft.

TODO:

- [x] #2517
- [x] Add units tests for probing in general and for the liquidity-stealing case in particular.

### CODE REVIEW

File: lightning-invoice/src/payment.rs [hunk 1]
```diff
@@ -163,6 +163,45 @@ fn pay_invoice_using_amount<P: Deref>(
...
+		SP::Target: SignerProvider,
+		F::Target: FeeEstimator,
+		R::Target: Router,
+		L::Target: Logger,
+{
+	let amount_msat = if let Some(invoice_amount_msat) = invoice.amount_milli_satoshis() {
+		invoice_amount_msat
+	} else {
+		return Err(PaymentError::Invoice("Failed to send probe as no amount was given in the invoice."));
+	};
```
Comment (benthecarman) [inline lightning-invoice/src/payment.rs:186]: Would be nice to be able to do this with amountless invoices. Could just add an optional amount param

File: lightning/src/ln/channelmanager.rs [hunk 2]
```diff
@@ -3452,6 +3452,88 @@ where
...
+
+					if first_hop.next_outbound_htlc_limit_msat
+						< (*used_liquidity + path_value)
+							* self.default_configuration.preflight_probing_liquidity_limit_multiplier
+					{
+						log_debug!(self.logger, "Skipped sending payment probe to avoid putting channel {} under the liquidity limit.", first_path_hop.short_channel_id);
+						continue;
+					} else {
+						*used_liquidity += path_value;
+					}
```
Comment (benthecarman) [inline lightning/src/ln/channelmanager.rs:3524]: should this filtering be done before `find_route` instead of the actual probing? you may get different routes than when paying the invoice, but would get you to actually probe all the paths instead of a subset.

File: lightning/src/util/config.rs [hunk 3]
```diff
@@ -764,6 +764,17 @@ pub struct UserConfig {
...
+	///
+	/// Channels with available liquidity less than the required amount times this value won't be
+	/// used to send pre-flight probes.
+	///
+	/// See [`ChannelManager::send_preflight_probes`] for more information.
+	///
+	/// Default value: 3
+	///
+	/// [`ChannelManager::send_preflight_probes`]: crate::ln::channelmanager::ChannelManager::send_preflight_probes
+	pub preflight_probing_liquidity_limit_multiplier: u64,
```
[the remark this answers is not in the document]
Comment (jkczyz) [reply lightning/src/util/config.rs:777]: Likewise.

File: lightning/src/ln/payment_tests.rs [hunk 4]
```diff
@@ -1304,6 +1305,107 @@ fn onchain_failed_probe_yields_event() {
...
+	}
+
+	let route_params = RouteParameters { payment_params, final_value_msat: 80_000_000 };
+	let res = nodes[0].node.send_preflight_probes(route_params).unwrap();
+
+	// We check that only one probe was sent, the other one was skipped due to limited liquidity.
+	assert_eq!(res.len(), 1);
+	let log_msg = format!("Skipped sending payment probe to avoid putting channel {} under the liquidity limit.",
+		first_chan_update.contents.short_channel_id);
+	node_cfgs[0].logger.assert_log_contains("lightning::ln::channelmanager", &log_msg, 1);
```
[the remark this answers is not in the document]
Comment (jkczyz) [reply lightning/src/ln/payment_tests.rs:1347]: It's a bit fragile and dependent on the implementation rather than the interface. Would prefer to have one test setup that doesn't skip any paths and another test with a different setup that does skip a path. I guess that may be a bit verbose without DRYing up the message handling.

File: lightning/src/ln/channelmanager.rs [hunk 5]
```diff
@@ -3539,7 +3539,29 @@ where
...
+				if last_path_hop.maybe_announced_channel {
+					// We found a potentially announced last hop.
+					break;
+				} else {
+					// Drop the last hop, as it's likely unannounced.
+					log_debug!(
+						self.logger,
+						"Avoided sending payment probe all the way to last hop {} as it is likely unannounced.",
+						last_path_hop.short_channel_id
+						);
```
Comment (jkczyz) [inline lightning/src/ln/channelmanager.rs:3569]: Indentation is off.

File: lightning/src/ln/channelmanager.rs [hunk 6]
```diff
@@ -3539,7 +3539,29 @@ where
...
+					let final_value_msat = path.final_value_msat();
+					path.hops.pop();
+					if let Some(new_last) = path.hops.iter_mut().last() {
```
Comment (jkczyz) [inline lightning/src/ln/channelmanager.rs:3572]: Would `last_mut()` work in place of `iter_mut().last()`?

File: lightning-invoice/src/payment.rs [hunk 7]
```diff
@@ -32,22 +32,13 @@ use core::time::Duration;
 /// with the same [`PaymentHash`] is never sent.
 ///
 /// If you wish to use a different payment idempotency token, see [`pay_invoice_with_id`].
-pub fn pay_invoice<M: Deref, T: Deref, ES: Deref, NS: Deref, SP: Deref, F: Deref, R: Deref, L: Deref>(
+pub fn pay_invoice<C: AChannelManager>(
 	invoice: &Bolt11Invoice, retry_strategy: Retry,
-	channelmanager: &ChannelManager<M, T, ES, NS, SP, F, R, L>
+	channelmanager: &C
```
Comment (jkczyz) [inline lightning-invoice/src/payment.rs:37]: Can put these parameters on one line here and elsewhere.

**Review by jkczyz — COMMENTED** [review]
Mostly minor things. The commit message for ae8f536de865c44afc03830b0bd8f2435fc1d8f5 could use details on the motivation.

File: lightning/src/routing/router.rs [hunk 8]
```diff
@@ -2472,17 +2482,38 @@ where L::Target: Logger {
...
+				details.is_public
+			} else {
+				// If we sourced it any other way, we double-check the network graph to see if
+				// there are announced channels between the endpoints. If so, the hop might be
+				// referring to any of the announced channels, as its `short_channel_id` might be
+				// an alias, in which case we don't take any chances here.
+				network_graph.node(&hop.node_id).map_or(false, |hop_node|
+					hop_node.channels.iter().any(|scid| network_graph.channel(*scid)
+							.map_or(false, |c| c.as_directed_from(&prev_hop_node_id).is_some()))
+					)
```
[the remark this answers is not in the document]
Comment (jkczyz) [reply lightning/src/routing/router.rs:2503]: Was referring to the closing parenthesis of the first `map_or`. The other indentation was right as you had it, I believe.
