### PR TITLE
Use `MonotonicTime` as `Instant` shifted by 10 years forward

### LINKED ISSUE #2311: Bug: On iOS LDK panics on reading scorer
### Current Behavior:
On iOS LDK panics on reading scorer with:
```
thread '<unnamed>' panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:424:33
```

### Expected Behavior:
LDK does not panic, but reads the scorer.

### Steps To Reproduce:
 1. Build and run a node with LDK on iOS
 2. Send coins (to have something to store for the scorer)
 3. Store the scorer
 3. Reboot the device
 4. Read the scorer file

### Environment
Device: iPhone8 and github MacOS builder.

### What Happens
Usually `std::time::Instant` uses duration since the device boot time.
Seems that iOS uses `u64` to store nanosecods, what means it cannot represent moments before the boot.

It breaks code at https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/routing/scoring.rs#L1727
```rust
    let mut duration_since_epoch = Duration::from_secs(0);
    // ...
      (4, duration_since_epoch, required),
    // ...
    let wall_clock_now = T::duration_since_epoch();
    let now = T::now();
    let last_updated = if wall_clock_now > duration_since_epoch {
        now - (wall_clock_now - duration_since_epoch)
        //  ^----- panics here
    } else { now };
```

 1. scorer writer writes *the moment of the event* as a duration since the Unix epoch
    `let duration_since_epoch = T::duration_since_epoch() - self.last_updated.elapsed`
 1. scorer reader reads *the moment of the event* as a duration since the Unix epoch to `duration_since_epoch`
 2. `wall_clock_now` is a `SystemTime`
 3. `wall_clock_now - duration_since_epoch` is the duration since *the event* (till now)
 4. `now` is `Instant`
 4. if there was a reboot between *the moment of the event* and now then `now` will have number of nanosecods since the boot what is shorter than `wall_clock_now - duration_since_epoch`
 5. `now - (wall_clock_now - duration_since_epoch)` panics

#### Simpler Test
```rust
    #[test]
    fn check_instant() {
        use std::time::{Duration, Instant};

        let now = Instant::now();
        let duration = Duration::from_secs(1);
        std::thread::sleep(duration);
        let after = Instant::now();
        // Learn how Instant is represented.
        eprintln!("moment {now:?} after {duration:?} is {after:?}");

        // One of the statement will likely fail.
        now.checked_sub(Duration::from_millis(1)).unwrap();
        now.checked_sub(Duration::from_millis(10)).unwrap();
        now.checked_sub(Duration::from_millis(100)).unwrap();
        now.checked_sub(Duration::from_secs(1)).unwrap();
        now.checked_sub(Duration::from_secs(10)).unwrap();
        now.checked_sub(Duration::from_secs(60)).unwrap();
        now.checked_sub(Duration::from_secs(10 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(30 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(2 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(4 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(8 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(12 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(24 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(10 * 24 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(100 * 24 * 60 * 60)).unwrap();
    }
```

### Conclusion
`Instant` can be compared (or subtracted) only with **other instances** of `Instant` (such that they stay within the duration of the program runtime). It is not supposed to be stored or interpreted in any other way.

From https://doc.rust-lang.org/std/time/struct.Instant.html:
> Instants are opaque types that can only be compared to one another. There is no method to get “the number of seconds” from an instant. Instead, it only allows measuring the duration between two instants (or comparing two instants).

### PR DESCRIPTION
**Pull request by andrei-21**
Such implementation allows `MonotonicTime` to go backward up to 10 years on all platforms. On some platforms (e.g. iOS) `Instant` is represented as `u64` of nanoseconds since the boot of the system. Obviously such implementation does not allow to go backward before the time of the boot.
Fixes #2311.

### CODE REVIEW

File: lightning/src/util/time.rs [hunk 1]
```diff
@@ -58,6 +58,48 @@ impl Sub<Duration> for Eternity {
...
+		if now.0 > earlier.0 { now.0 - earlier.0 } else { Duration::from_secs(0) }
+	}
+
+	fn duration_since_epoch() -> Duration {
+		use std::time::SystemTime;
+		SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap()
+	}
+
+	fn elapsed(&self) -> Duration {
+		self.0.elapsed()
```
Comment (jkczyz) [inline lightning/src/util/time.rs:89]: Won't this result in an underflow? `Instant::elapsed` uses `Instant::now() - *self`.

Also, note that this method is used in `Writeable for ChannelLiquidity<T>`.

File: lightning/src/util/time.rs [hunk 2]
```diff
@@ -58,6 +58,48 @@ impl Sub<Duration> for Eternity {
 	}
 }
 
+#[derive(Clone, Copy, Debug, PartialEq, Eq)]
+#[cfg(not(feature = "no-std"))]
+pub struct MonotonicTime(std::time::Instant);
+#[cfg(not(feature = "no-std"))]
+static SHIFT: Duration = Duration::from_secs(10 * 365 * 24 * 60 * 60); // 10 years.
```
Comment (jkczyz) [inline lightning/src/util/time.rs:65]: Could you add a comment here on why this value was chosen?

File: lightning/src/routing/scoring.rs [hunk 3]
```diff
@@ -325,7 +325,7 @@ impl ReadableArgs<u64> for FixedPenaltyScorer {
 }
 
 #[cfg(not(feature = "no-std"))]
-type ConfiguredTime = std::time::Instant;
+type ConfiguredTime = crate::util::time::MonotonicTime;
```
Comment (jkczyz) [inline lightning/src/routing/scoring.rs:328]: Should we replace the custom handling in `Readable for ChannelLiquidity<T>`?

**Comment by jkczyz** [comment]
> > Such implementation allows `MonotonicTime` to go backward up to 10 years on all platforms. On some platforms (e.g. iOS) `Instant` is represented as `u64` of nanoseconds since the boot of the system. Obviously such implementation does not allow to go backward before the time of the boot. Fixes #2311.
> 
> I don't think this fix pertains to the system time not being monotonic. That should already be fixed in the `Readable` implementation for `ChannelLiquidity`. Instead, this fixes a problem where a platform can't represent an `Instance` sometime prior to the system boot. I'll push a commit adding docs to say as much.

Ah, you can disregard this argument. I see what you were saying, but I'll push the doc change regardless.

File: lightning/src/util/time.rs (hunk 2 above)
Comment (jkczyz) [reply lightning/src/util/time.rs:68]: Added in new push.

File: lightning/src/util/time.rs [hunk 4]
```diff
@@ -180,7 +180,10 @@ pub mod tests {
 	#[cfg(not(feature = "no-std"))]
 	fn monotonic_time_go_backward() {
```
Comment (jkczyz) [inline lightning/src/util/time.rs:181]: Could you name this `monotonic_time_subtracts`?

File: lightning/src/util/time.rs (hunk 1 above)
Comment (jkczyz) [reply lightning/src/util/time.rs]: lol, yeah, I confused myself. The subtraction occurs in `Instant::elapsed`, but the test that I wrote wasn't catching the failure.

**Review by jkczyz — COMMENTED** [review]
Please go ahead and squash the fixup and the forthcoming test rename. Otherwise, seems good to go.

**Review by jkczyz — DISMISSED** [review]

**Review by jkczyz — APPROVED** [review]
