### PR TITLE
Drop dep `tokio`'s `io-util` feat as it broke MSRV and isn't useful

### LINKED ISSUE #2527: CI failures running Rust 1.48 and 1.49 on ubuntu-latest and windows-latest
The Cargo manifest cannot be parsed due to a serde dependency with version 1.0.187. 

Here's an example of CI failing: https://github.com/lightningdevkit/rust-lightning/actions/runs/5979401369/job/16223410901

### PR DESCRIPTION
**Pull request by TheBlueMatt**
We use `tokio`'s `io-util` feature to provide the
`Async{Read,Write}Ext` traits, which allow us to simply launch a read future or `poll_write` directly as well as `split` the `TcpStream` into a read/write half. However, these traits aren't actually doing much for us - they are really just wrapping the `readable` future (which we can trivially use ourselves) and `poll_write` isn't doing anything for us that `poll_write_ready` can't.

Similarly, the split logic is actually just `Arc`ing the `TcpStream` and busy-waiting when an operation is busy to prevent concurrent reads/writes. However, there's no reason to prevent concurrent access at the stream level - we aren't ever concurrently writing or reading (though we may concurrently read and write, which is fine).

Worse, the `io-util` feature broke MSRV (though they're likely to fix this upstream) and carries two additional dependencies (only one on the latest upstream tokio).

Thus, we simply drop the dependency here.

Fixes #2527.

### CODE REVIEW

**Comment by jkczyz** [comment]
CI still unhappy 😭 

```
+ cargo check --verbose --color always
    Updating crates.io index
    Updating git repository `[https://github.com/arik-so/rust-musig2`](https://github.com/arik-so/rust-musig2%60)
 Downloading crates ...
  Downloaded memchr v2.6.0
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.6.0/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
Error: Process completed with exit code 101.
```

File: lightning-net-tokio/src/lib.rs [hunk 1]
```diff
@@ -462,9 +463,9 @@ impl SocketDescriptor {
 }
 impl peer_handler::SocketDescriptor for SocketDescriptor {
 	fn send_data(&mut self, data: &[u8], resume_read: bool) -> usize {
-		// To send data, we take a lock on our Connection to access the WriteHalf of the TcpStream,
-		// writing to it if there's room in the kernel buffer, or otherwise create a new Waker with
-		// a SocketDescriptor in it which can wake up the write_avail Sender, waking up the
+		// To send data, we take a lock on our Connection to access the TcpStream, writing to it if
+		// there's room in the kernel buffer, or otherwise create a new Waker with a
+		// SocketDescriptor  in it which can wake up the write_avail Sender, waking up the
```
Comment (jkczyz) [inline lightning-net-tokio/src/lib.rs:468]: nit: extra space after `SocketDescriptor`

**Review by jkczyz — COMMENTED** [review]
LGTM

**Review by jkczyz — APPROVED** [review]
