### PR TITLE
Ignore .tmp files when loading ChannelMonitors in persister

### LINKED ISSUE #1330: `lightning-persister` refuses to load if we previously crashed during persistence
Specifically, we hit `Invalid tx index in filename` when there's a file with a `.tmp` lying around, which we shouldn't cause that is just indicative of a previous persistence that was in-flight when we died.

### PR DESCRIPTION
**Pull request by TheBlueMatt**
If we are in the middle of persisting an update to a
`ChannelMonitor` when we shutdown (or crash), we'll start up with
a .tmp file lying around. We should ignore it, as failure to
return from the update call should have prevented the
`ChannelManager` from taking any irrevocable action based on the
update.

We're somewhat protected from any filesystem inconsistency behavior
as the `ChannelManager` will refuse to load if we're outright
missing `ChannelMonitor`s.

Fixes #1330.

### CODE REVIEW

File: lightning-persister/src/lib.rs [hunk 1]
```diff
@@ -122,6 +122,12 @@ impl FilesystemPersister {
 					"Invalid ChannelMonitor file name",
 				));
 			}
+			if filename.ends_with(".tmp") {
```
Comment (jkczyz) [inline lightning-persister/src/lib.rs:125]: Looks like you need an `unwrap`.

**Review by jkczyz — APPROVED** [review]

**Review by valentinewallace — APPROVED** [review]

**Comment by TheBlueMatt** [comment]
Allowed fuzz failures until we fix the honggfuzz-rs issue.
