### PR TITLE
Correct `peer_handler::test_process_events_multithreaded`

### LINKED ISSUE #2385: `Process_events_multithreaded` is flaky
CI on latest main said:

```

failures:

---- ln::peer_handler::tests::test_process_events_multithreaded stdout ----
thread 'ln::peer_handler::tests::test_process_events_multithreaded' panicked at 'assertion failed: val <= 2', lightning/src/ln/peer_handler.rs:3153:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dbf31f17d020475885f50fb7d5fc15ff239843d8/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/dbf31f17d020475885f50fb7d5fc15ff239843d8/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/dbf31f17d020475885f50fb7d5fc15ff239843d8/library/core/src/panicking.rs:117:5
   3: lightning::ln::peer_handler::tests::test_process_events_multithreaded
             at ./src/ln/peer_handler.rs:3153:4
   4: lightning::ln::peer_handler::tests::test_process_events_multithreaded::{{closure}}
             at ./src/ln/peer_handler.rs:3117:41
   5: core::ops::function::FnOnce::call_once
             at /rustc/dbf31f17d020475885f50fb7d5fc15ff239843d8/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/dbf31f17d020475885f50fb7d5fc15ff239843d8/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    ln::peer_handler::tests::test_process_events_multithreaded

test result: FAILED. 723 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 22.38s
```

### PR DESCRIPTION
**Pull request by TheBlueMatt**
This test was added some time ago in
0c034e9a82e4339fb32af9da63832ac2a64abb0b, but never made any sense. `PeerManager::process_events` will go around its loop as many times is required to ensure we've always processed all events which were pending prior to a `process_events` call, so having a test that checks that we never go around more than twice is obviously broken.

And, indeed, in CI this tests fails with some regularity.

Instead, the test here is changed to ensure that we detectably go around the loop again at least once.

Fixes #2385

### CODE REVIEW

File: lightning/src/ln/peer_handler.rs [hunk 1]
```diff
@@ -3452,48 +3452,45 @@ mod tests {
...
-
-		let thread_a = spawn_thread!();
-		let thread_b = spawn_thread!();
-		let thread_c = spawn_thread!();
-
-		let start_time = Instant::now();
-		while start_time.elapsed() < Duration::from_millis(100) {
-			let val = cfg[0].chan_handler.message_fetch_counter.load(Ordering::Acquire);
-			assert!(val <= 2);
-			std::thread::yield_now(); // Winblowz seemingly doesn't ever interrupt threads?!
```
Comment (valentinewallace) [inline lightning/src/ln/peer_handler.rs:3490]: Do we still need this fix?

**Review by valentinewallace — APPROVED** [review]
LGTM. Merging with 1 ack since it's just a test change
