### PR TITLE
Fix race condition in async `UtxoFuture` resolution 

### LINKED ISSUE #4346: gossip doesnt resolve async
@tnull discovered that after #4294 we drop the arc after resolving it and because the pending resolutions logic only keeps `Weak`s we end up never being able to process resolutions because the data is gone. Need to fix before 0.3 goes out so we don't regress.

### PR DESCRIPTION
**Pull request by tnull**
Fixes #4346.

Previously, we refactored the `GossipVerifier` to not require holding a
circular reference. As part of this, we moved to a model where the
`UtxoFuture`s are now polled by the background processor which checks
for completion through `get_and_clear_pending_msg_events`.

However, as part of this refactor we introduced race-condition: as we
only held `Weak` references in `PendingChecksContext` and the
`UtxoFuture` was directly dropped by the `GossipVerifier` after calling
`resolve`, the actual data was dropped with the future and gone when the
background processor attempted to retrieve and apply it via
`check_resolved_futures`.

Here, we fix this issue by simply holding on to the `state` `Arc`s in a
separate `pending_states` `Vec` that is only pruned in
`check_resolved_futures`, ensuring any completed results are collected
first.

### CODE REVIEW

File: lightning/src/routing/utxo.rs [hunk 1]
```diff
@@ -595,35 +631,58 @@ mod tests {
...
+
+		(
+			valid_announcement,
+			chain_source,
+			network_graph,
+			good_script,
+			node_a_announce,
+			node_b_announce,
+			chan_update_a,
+			chan_update_b,
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs]: Wanna just inline the builders here? There's not really any reason for the intermediate variables at this point.

File: lightning/src/routing/utxo.rs [hunk 2]
```diff
@@ -637,44 +696,81 @@ mod tests {
...
 
-		network_graph.update_channel_from_announcement(&valid_announcement, &Some(&chain_source)).unwrap();
-		assert!(network_graph.read_only().channels().get(&valid_announcement.contents.short_channel_id).is_some());
+		network_graph
+			.update_channel_from_announcement(&valid_announcement, &Some(&chain_source))
+			.unwrap();
+		assert!(network_graph
+			.read_only()
+			.channels()
+			.get(&valid_announcement.contents.short_channel_id)
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs]: There's a bunch of places here where we could reasonably replace things like `valid_announcement.contents.short_channel_id` with an `scid` and make the whole thing more readable.

File: lightning/src/routing/utxo.rs [hunk 3]
```diff
@@ -706,103 +813,193 @@ mod tests {
...
 		assert_eq!(chan_update_a.contents.timestamp, chan_update_b.contents.timestamp);
 		let graph_lock = network_graph.read_only();
-		assert!(graph_lock.channels()
-				.get(&valid_announcement.contents.short_channel_id).as_ref().unwrap()
-				.one_to_two.as_ref().unwrap().last_update !=
-			graph_lock.channels()
-				.get(&valid_announcement.contents.short_channel_id).as_ref().unwrap()
-				.two_to_one.as_ref().unwrap().last_update);
+		assert!(
+			graph_lock
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs]: lol this is definitely not readable, vertical or not my eyes cannot parse this.

File: lightning/src/routing/utxo.rs [hunk 4]
```diff
@@ -843,14 +1053,20 @@ mod tests {
...
 		network_graph.pending_checks.check_resolved_futures(&network_graph);
-		assert!(!network_graph.read_only().channels()
-			.get(&valid_announcement.contents.short_channel_id).unwrap()
-			.announcement_message.as_ref().unwrap()
-			.contents.features.supports_unknown_test_feature());
+		assert!(!network_graph
+			.read_only()
+			.channels()
+			.get(&valid_announcement.contents.short_channel_id)
+			.unwrap()
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs]: same here. the `rustfmt` behavior of treating things like `as_ref().unwrap()` as "equally important" as ".get(X) or ".features" makes this so hard to follow.

File: lightning/src/routing/utxo.rs [hunk 5]
```diff
@@ -464,7 +464,7 @@ impl PendingChecks {
 			// If we have many channel checks pending, ensure we don't have any dangling checks
 			// (i.e. checks where the user told us they'd call back but drop'd the `UtxoFuture`
 			// instead) before we commit to applying backpressure.
-			pending_checks.channels.retain(|_, chan| Weak::upgrade(&chan).is_some());
+			pending_checks.channels.retain(|_, chan| Arc::strong_count(chan) > 1);
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs]: Can't this race `check_resolved_futures` and hit the same issue that we're fixing again?

File: lightning/src/routing/utxo.rs [hunk 6]
```diff
@@ -284,22 +285,31 @@ impl PendingChecks {
...
-				// lookup if we haven't gotten that far yet).
-				match Weak::upgrade(&e.get()) {
-					Some(pending_msgs) => {
-						// This may be called with the mutex held on a different UtxoMessages
-						// struct, however in that case we have a global lockorder of new messages
-						// -> old messages, which makes this safe.
-						let pending_matches = match &pending_msgs
-							.unsafe_well_ordered_double_lock_self()
-							.channel_announce
+				if Arc::strong_count(e.get()) == 1 {
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs]: Shouldn't we limit this to `strong_count == 1 && !resolved`? Not exactly critical but if we did just finish validating a channel update and we get a copy of it from a peer we should let the old one finish getting handled in `check_resolved_futures` rather than dropping it and immediately starting another validation.

File: lightning/src/routing/utxo.rs [hunk 7]
```diff
@@ -194,9 +194,13 @@ impl PendingChecks {
 	) -> Result<(), LightningError> {
 		let mut pending_checks = self.internal.lock().unwrap();
 		if let hash_map::Entry::Occupied(e) = pending_checks.channels.entry(msg.short_channel_id) {
-			let is_from_a = (msg.channel_flags & 1) == 1;
-			match Weak::upgrade(e.get()) {
-				Some(msgs_ref) => {
+			if Arc::strong_count(e.get()) == 1 {
+				// The future was dropped and the entry is the last reference held.
+				e.remove();
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs]: This basically re-introduces the bug we're trying to fix in a (hopefully rare) race but by receiving a `channel_announcement` right after we finish processing some gossip.

File: lightning/src/routing/utxo.rs [hunk 8]
```diff
@@ -194,9 +194,13 @@ impl PendingChecks {
 	) -> Result<(), LightningError> {
 		let mut pending_checks = self.internal.lock().unwrap();
 		if let hash_map::Entry::Occupied(e) = pending_checks.channels.entry(msg.short_channel_id) {
-			let is_from_a = (msg.channel_flags & 1) == 1;
-			match Weak::upgrade(e.get()) {
-				Some(msgs_ref) => {
+			if Arc::strong_count(e.get()) == 1 {
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs]: Shouldn't we limit this to `strong_count == 1 && !resolved`? If we get an update and we have a pending resolution that just finished we should just set the update to handle.

File: lightning/src/routing/utxo.rs (hunk 5 above)
Comment (tnull) [reply lightning/src/routing/utxo.rs]: Yes, potentially. Note that I'm still experimenting with the approach and am not yet fully sold on going the strong count, as, even if we get it just right now, we could could easily mess it up again going forward. Please defer reviewing until this is undrafted.

File: lightning/src/routing/utxo.rs (hunk 7 above)
Comment (tnull) [reply lightning/src/routing/utxo.rs]: Yes, I'm aware. I had dropped it before and added it back for experimentation purposes. Please hold on review until this is undrafted.

File: lightning/src/routing/utxo.rs (hunk 1 above)
Comment (tnull) [reply lightning/src/routing/utxo.rs]: Not sure that's preferable. Now went ahead and did it though.

File: lightning/src/routing/utxo.rs (hunk 2 above)
Comment (tnull) [reply lightning/src/routing/utxo.rs]: Done.

File: lightning/src/routing/utxo.rs (hunk 3 above)
Comment (tnull) [reply lightning/src/routing/utxo.rs]: Fixed.

File: lightning/src/routing/utxo.rs (hunk 4 above)
Comment (tnull) [reply lightning/src/routing/utxo.rs]: Fixed.

**Review by tnull — COMMENTED** [review]
Now switched to a much less invasive approach where we simply keep track of the pending future states `Arc`s in a separate `Vec` until the next call of `check_resolved_futures`, which will collect completed states and prune the data structures.

**Comment by tnull** [comment]
Whoops, seems there are still some more tests to fix, drafting again :hand_over_mouth:

**Comment by tnull** [comment]
> Whoops, seems there are still some more tests to fix, drafting again 🤭

... and they're passing again.

File: lightning/src/routing/utxo.rs [hunk 9]
```diff
@@ -637,204 +722,298 @@ mod tests {
...
+		network_graph.read_only().channels().get(&scid).unwrap();
+		network_graph.read_only().channels().get(&scid).unwrap();
 
-		assert!(network_graph.read_only().nodes().get(&valid_announcement.contents.node_id_1)
-			.unwrap().announcement_info.is_none());
+		assert!(network_graph
+			.read_only()
+			.nodes()
+			.get(&node_id_1)
+			.unwrap()
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs]: These are also pretty borderline (there's a few more further down).

File: lightning/src/routing/utxo.rs (hunk 4 above)
Comment (TheBlueMatt) [reply lightning/src/routing/utxo.rs]: Still the same on the latest version?

**Comment by tnull** [comment]
> Bleh, don't love the extra vec but you're right that its much simpler and probably worth it. Feel free to squash (maybe with a few more rustfmt'isms fixed) and let's land this.

Squashed fixup, and included the following changes:

```diff
diff --git a/lightning/src/routing/utxo.rs b/lightning/src/routing/utxo.rs
index f3351aa0a..ab653b1ea 100644
--- a/lightning/src/routing/utxo.rs
+++ b/lightning/src/routing/utxo.rs
@@ -763,22 +763,16 @@ mod tests {
                network_graph.read_only().channels().get(&scid).unwrap();

-               assert!(network_graph
-                       .read_only()
-                       .nodes()
-                       .get(&node_id_1)
-                       .unwrap()
-                       .announcement_info
-                       .is_none());
+               #[rustfmt::skip]
+               let is_node_a_announced = network_graph.read_only().nodes().get(&node_id_1).unwrap()
+                       .announcement_info.is_some();
+               assert!(!is_node_a_announced);

                network_graph.update_node_from_announcement(&node_a_announce).unwrap();
                network_graph.update_node_from_announcement(&node_b_announce).unwrap();

-               assert!(network_graph
-                       .read_only()
-                       .nodes()
-                       .get(&node_id_1)
-                       .unwrap()
-                       .announcement_info
-                       .is_some());
+               #[rustfmt::skip]
+               let is_node_a_announced = network_graph.read_only().nodes().get(&node_id_1).unwrap()
+                       .announcement_info.is_some();
+               assert!(is_node_a_announced);
        }

@@ -1023,15 +1017,9 @@ mod tests {
                assert!(!notifier_b.notify_pending());
                network_graph.pending_checks.check_resolved_futures(&network_graph);
-               assert!(!network_graph
-                       .read_only()
-                       .channels()
-                       .get(&scid)
-                       .unwrap()
-                       .announcement_message
-                       .as_ref()
-                       .unwrap()
-                       .contents
-                       .features
-                       .supports_unknown_test_feature());
+               #[rustfmt::skip]
+               let is_test_feature_set =
+                       network_graph.read_only().channels().get(&scid).unwrap().announcement_message
+                       .as_ref().unwrap().contents.features.supports_unknown_test_feature();
+               assert!(!is_test_feature_set);
        }

```

File: lightning/src/routing/utxo.rs (hunk 4 above)
Comment (tnull) [reply lightning/src/routing/utxo.rs]: Ah, didn't deem this worthy a `rustfmt::skip`. Now fixed in the last push.

File: lightning/src/routing/utxo.rs (hunk 9 above)
Comment (tnull) [reply lightning/src/routing/utxo.rs]: Pulled out into a variable and added a `rustfmt::skip` here.

File: lightning/src/routing/utxo.rs [hunk 10]
```diff
@@ -637,204 +722,292 @@ mod tests {
...
 		assert!(notifier.notify_pending());
 		network_graph.pending_checks.check_resolved_futures(&network_graph);
-		network_graph.read_only().channels().get(&valid_announcement.contents.short_channel_id).unwrap();
-		network_graph.read_only().channels().get(&valid_announcement.contents.short_channel_id).unwrap();
+		network_graph.read_only().channels().get(&scid).unwrap();
+		network_graph.read_only().channels().get(&scid).unwrap();
 
-		assert!(network_graph.read_only().nodes().get(&valid_announcement.contents.node_id_1)
-			.unwrap().announcement_info.is_none());
+		#[rustfmt::skip]
```
Comment (TheBlueMatt) [inline lightning/src/routing/utxo.rs:765]: Not really sure that `rustfmt::skip` is the right fix for these kinds of cases. We can take intermediate variables that clean up rustfmt's crap and improve readability while we're at it.

**Review by TheBlueMatt — APPROVED** [review]
thanks. just gonna land this it ended up being relatively trivial.
