### PR TITLE
Fix off-by-one finalized transaction locktime

### LINKED ISSUE #2181: Core rejected expired HTLC claim as too soon
Just saw my sample node try to broadcast an expired HTLC claim on-chain but it got rejected for a locktime failure. The transaction's locktime was one higher than the block height being connected, which it got from the same bitcoind, so it *should* have made it into the mempool. I wonder if there's some bug in core or race condition there where the mempool hasn't been updated yet? It seemed to only get broadcasted an hour (and a number of blocks) later when I did it manually (but I assume we'd have rebroadcasted it again after some number of blocks? I hope?).

### PR DESCRIPTION
**Pull request by wpaulino**
While these transactions were still valid, we incorrectly assumed that they would propagate with a locktime of `current_height + 1`, when in reality, only those with a locktime strictly lower than the next height in the chain are allowed to enter the mempool.

Fixes #2181.

### CODE REVIEW

File: lightning/src/chain/onchaintx.rs [hunk 1]
```diff
@@ -1036,8 +1036,10 @@ impl<ChannelSigner: WriteableEcdsaChannelSigner> OnchainTxHandler<ChannelSigner>
 			}
 		}
 		for ((_package_id, _), ref mut request) in bump_candidates.iter_mut() {
+			// `height` is the height being disconnected, so our `current_height` is 1 lower.
```
Comment (ariard) [inline lightning/src/chain/onchaintx.rs:1039]: Trying to claim at next block connection works well, until a user calls `invalidateblock` and break this assumption, I think (though it’s a quite unorthodox uses of the consensus engine).
