### PR TITLE
Stop decaying liquidity information during scoring

### LINKED ISSUE #2311: Bug: On iOS LDK panics on reading scorer
### Current Behavior:
On iOS LDK panics on reading scorer with:
```
thread '<unnamed>' panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:424:33
```

### Expected Behavior:
LDK does not panic, but reads the scorer.

### Steps To Reproduce:
 1. Build and run a node with LDK on iOS
 2. Send coins (to have something to store for the scorer)
 3. Store the scorer
 3. Reboot the device
 4. Read the scorer file

### Environment
Device: iPhone8 and github MacOS builder.

### What Happens
Usually `std::time::Instant` uses duration since the device boot time.
Seems that iOS uses `u64` to store nanosecods, what means it cannot represent moments before the boot.

It breaks code at https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/routing/scoring.rs#L1727
```rust
    let mut duration_since_epoch = Duration::from_secs(0);
    // ...
      (4, duration_since_epoch, required),
    // ...
    let wall_clock_now = T::duration_since_epoch();
    let now = T::now();
    let last_updated = if wall_clock_now > duration_since_epoch {
        now - (wall_clock_now - duration_since_epoch)
        //  ^----- panics here
    } else { now };
```

 1. scorer writer writes *the moment of the event* as a duration since the Unix epoch
    `let duration_since_epoch = T::duration_since_epoch() - self.last_updated.elapsed`
 1. scorer reader reads *the moment of the event* as a duration since the Unix epoch to `duration_since_epoch`
 2. `wall_clock_now` is a `SystemTime`
 3. `wall_clock_now - duration_since_epoch` is the duration since *the event* (till now)
 4. `now` is `Instant`
 4. if there was a reboot between *the moment of the event* and now then `now` will have number of nanosecods since the boot what is shorter than `wall_clock_now - duration_since_epoch`
 5. `now - (wall_clock_now - duration_since_epoch)` panics

#### Simpler Test
```rust
    #[test]
    fn check_instant() {
        use std::time::{Duration, Instant};

        let now = Instant::now();
        let duration = Duration::from_secs(1);
        std::thread::sleep(duration);
        let after = Instant::now();
        // Learn how Instant is represented.
        eprintln!("moment {now:?} after {duration:?} is {after:?}");

        // One of the statement will likely fail.
        now.checked_sub(Duration::from_millis(1)).unwrap();
        now.checked_sub(Duration::from_millis(10)).unwrap();
        now.checked_sub(Duration::from_millis(100)).unwrap();
        now.checked_sub(Duration::from_secs(1)).unwrap();
        now.checked_sub(Duration::from_secs(10)).unwrap();
        now.checked_sub(Duration::from_secs(60)).unwrap();
        now.checked_sub(Duration::from_secs(10 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(30 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(2 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(4 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(8 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(12 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(24 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(10 * 24 * 60 * 60)).unwrap();
        now.checked_sub(Duration::from_secs(100 * 24 * 60 * 60)).unwrap();
    }
```

### Conclusion
`Instant` can be compared (or subtracted) only with **other instances** of `Instant` (such that they stay within the duration of the program runtime). It is not supposed to be stored or interpreted in any other way.

From https://doc.rust-lang.org/std/time/struct.Instant.html:
> Instants are opaque types that can only be compared to one another. There is no method to get “the number of seconds” from an instant. Instead, it only allows measuring the duration between two instants (or comparing two instants).

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Because scoring is an incredibly performance-sensitive operation,
doing liquidity information decay (and especially fetching the
current time!) during scoring isn't really a great idea. Instead, this PR moves to handling decaying in a background processor job.

This should fix #2311, which apparently is still an issue for some users as of 0.0.116.

There was some discussion of an alternative approach where we fetch the time at the start of a routefinding session, store it on the stack, and pass it through to the scorer as we go. I opted not to do this because (a) bindings can't map unbounded generics, which this would need, (b) this avoids actually doing the decay during scoring at all, which probably saves an ms or two, though certainly not a ton, (c) this leads to a much nicer/simpler API - we can remove `Time`, which we either need to remove or make public (see #2497), and can drop the excess type alias, both of which are much nicer than the alternative. I'm open to more discussion here, but the cost of having one more thing to call as time moves forward doesn't seem high enough to outweigh a, b, and c here.

### CODE REVIEW

File: lightning-background-processor/src/lib.rs [hunk 1]
```diff
@@ -239,30 +239,30 @@ fn handle_network_graph_update<L: Deref>(
...
-			score.probe_successful(path);
+			score.probe_successful(path, duration_since_epoch);
 		},
 		Event::ProbeFailed { path, short_channel_id: Some(scid), .. } => {
 			let mut score = scorer.write_lock();
-			score.probe_failed(path, *scid);
+			score.probe_failed(path, *scid, duration_since_epoch);
 		},
 		_ => return false,
 	}
```
Comment (jkczyz) [inline lightning-background-processor/src/lib.rs:268]: Won't this mean channels along recently used paths will have their offsets decayed but other channels will not?

Comment (jkczyz) [reply lightning-background-processor/src/lib.rs:268]: Maybe I'm confused, but it looks like we only decay once per hour in the background processor.

File: lightning/src/routing/scoring.rs [hunk 2]
```diff
@@ -1228,119 +1232,102 @@ impl<L: Deref<Target = u64>, BRT: Deref<Target = HistoricalBucketRangeTracker>,
...
 
 	/// Updates the history buckets for this channel. Because the history buckets track what we now
 	/// know about the channel's state *prior to our payment* (i.e. what we assume is "steady
 	/// state"), we allow the caller to set an offset applied to our liquidity bounds which
 	/// represents the amount of the successful payment we just made.
-	fn update_history_buckets(&mut self, bucket_offset_msat: u64) {
-		let half_lives = self.now.duration_since(*self.last_updated).as_secs()
+	fn update_history_buckets(&mut self, bucket_offset_msat: u64, duration_since_epoch: Duration) {
+		let half_lives =
+			duration_since_epoch.checked_sub(*self.offset_history_last_updated)
```
Comment (jkczyz) [inline lightning/src/routing/scoring.rs:1294]: This isn't accurate given that `offset_history_last_updated` is updated in `set_min_liquidity_msat` and `set_max_liquidity_msat` which could (but may not) be called prior to calling `update_history_buckets`. Do we have tests to catch this?

**Review by jkczyz — COMMENTED** [review]
> There was some discussion of an alternative approach where we fetch the time at the start of a routefinding session, store it on the stack, and pass it through to the scorer as we go. I opted not to do this because (a) bindings can't map unbounded generics, which this would need, (b) this avoids actually doing the decay during scoring at all, which probably saves an ms or two, though certainly not a ton, (c) this leads to a much nicer/simpler API - we can remove `Time`, which we either need to remove or make public (see #2497), and can drop the excess type alias, both of which are much nicer than the alternative. I'm open to more discussion here, but the cost of having one more thing to call as time moves forward doesn't seem high enough to outweigh a, b, and c here.

Hmmm... (a) can be avoided if we use a `Duration` since we have `Time::duration_since_epoch`. (b) seem negligible. And I'm not entirely convinced on (c) regarding the API as now `Duration` is used in the mutable but not the non-mutable interface, which isn't vert intuitive in places (see comments). Also, there's the risk of adding new bugs.

File: lightning-background-processor/src/lib.rs [hunk 3]
```diff
@@ -773,7 +796,10 @@ impl BackgroundProcessor {
 					handle_network_graph_update(network_graph, &event)
 				}
 				if let Some(ref scorer) = scorer {
-					if update_scorer(scorer, &event) {
+					use std::time::SystemTime;
```
Comment (benthecarman) [inline lightning-background-processor/src/lib.rs:799]: since this functions uses system time now, it should probably be `#[cfg(all(feature = "std"), not(feature = "no-std")]` to handle when you'll be able to use both flags together in the future

File: lightning/src/routing/scoring.rs [hunk 4]
```diff
@@ -1446,29 +1423,70 @@ impl<G: Deref<Target = NetworkGraph<L>>, L: Deref, T: Time> ScoreUpdate for Prob
...
+				if half_life != 0.0 {
+					let divisor = powf64(2048.0, elapsed_time.as_secs_f64() / half_life) as u64;
+					for bucket in liquidity.min_liquidity_offset_history.buckets.iter_mut() {
+						*bucket = ((*bucket as u64) * 1024 / divisor) as u16;
+					}
+					for bucket in liquidity.max_liquidity_offset_history.buckets.iter_mut() {
+						*bucket = ((*bucket as u64) * 1024 / divisor) as u16;
+					}
+					liquidity.offset_history_last_updated = duration_since_epoch;
+				}
```
Comment (jkczyz) [inline lightning/src/routing/scoring.rs:1467]: IIUC, this means we'll decay partial half-lives but only after decaying one full half-life. Why bother with using `2048.0` and `1024` here if this is happening in the background?

Comment (jkczyz) [reply lightning/src/routing/scoring.rs:1467]: But why not do partial decays when less than one half-life has passed?

File: lightning-background-processor/src/lib.rs [hunk 5]
```diff
@@ -1700,7 +1732,7 @@ mod tests {
 						_ = exit_receiver.changed() => true,
 					}
 				})
-			}, false,
+			}, false, || Some(Duration::from_secs(1696300000)),
```
[the remark this answers is not in the document]
Comment (jkczyz) [reply lightning-background-processor/src/lib.rs:1735]: Given the value doesn't affect the test, it's just curious to the reader to see something different from all the other places.

File: lightning-background-processor/src/lib.rs (hunk 1 above)
Comment (jkczyz) [reply lightning-background-processor/src/lib.rs:273]: > All that said, I'm not really convinced either is a super critical issue, at least if we decay more often, at max we'd be off by a small part of a half-life.

Hmm... if one offset is updated frequently, you'll get into a state where the other offset is only ever partially decayed even though it may have been given that value many half-lives ago. So would really depend on both payment and decay frequency.

File: lightning/src/routing/scoring.rs (hunk 4 above)
Comment (jkczyz) [reply lightning/src/routing/scoring.rs:1467]: I see, SGTM.

**Comment by jkczyz** [comment]
Code overall looks good. I'm not opposed to the approach, necessarily. I *think* there still can be an issue decaying in the case of a node with a large payment volume (See https://github.com/lightningdevkit/rust-lightning/pull/2656#discussion_r1427431125).

Otherwise, I don't have any other concerns. @tnull Could you take another look?

File: lightning-background-processor/src/lib.rs (hunk 1 above)
Comment (jkczyz) [reply lightning-background-processor/src/lib.rs:273]: FWIW, that's not the only scenario. Failures at a channel and downstream from it adjust it's upper and lower bounds, respectively. So if you fail downstream with increasing amounts, the upper bound may not be properly decayed.

**Comment by jkczyz** [comment]
> Yea, I mean its definitely not "right", just not clear to me its "wrong" either. The only thing we could really do to address it is split the last_updated fields into two. I'm totally fine doing that if you think its worth it.

I guess it just can come across as surprising to an outside observer. They can tell that the a bound has been adjusted, but one of them doesn't seem to be decaying as expected based on the configuration and the observed time of adjustment. Maybe it's not horrible in practice?

File: lightning-background-processor/src/lib.rs (hunk 1 above)
Comment (jkczyz) [reply lightning-background-processor/src/lib.rs:273]: Not necessarily for the same payment or at the same downstream channel. From the perspective of the scored channel, it's simply the normal case of learning a more accurate lower bound on its liquidity as a consequence of knowing a payment routed through it but failed downstream.

**Comment by jkczyz** [comment]
> I guess to an outside observer it just looks like both ends got updated? Which isn't true, but not crazy broken either (at least in the sense that I'm not sure what outside observer would be looking at both their failures and their success/failure stream and somehow caring about the inconsistent decays). I'm happy with either solution, though - as-is or splitting the last-updated tracking. We could also split the last-updated tracking in a followup, it'd be a new commit either way.

Was thinking in terms of something like `estimated_channel_liquidity_range` and a prober that may use the data to make decisions on future probes. An outsider can observe the bounds changing over time and from events.

But, yeah, a follow-up is fine. Seems like we can always do it later if we find problems, too, given the serialization format. Just seems more correct to use separate timestamps.

**Review by jkczyz — APPROVED** [review]

File: lightning/src/routing/scoring.rs [hunk 6]
```diff
@@ -3516,8 +3458,6 @@ mod tests {
 			};
 
 			assert_eq!(scorer.channel_penalty_msat(&candidate, usage, &params), 2050);
-			usage.inflight_htlc_msat = 0;
-			assert_eq!(scorer.channel_penalty_msat(&candidate, usage, &params), 866);
```
Comment (jkczyz) [inline lightning/src/routing/scoring.rs:3520]: Was just fixing a build warning and noticed this. Why did this check need to be removed? Deleted in 35b49645c4eb0d61c162a502723cd4e44ef0ca1e.
