### PR TITLE
Accuracy fixes and differentiating sources for `Balance` 

### LINKED ISSUE #2738: Differentiate between coop close and force-close in `Balance`
There is no way to tell whether a `Balance` is for a coop close or an HTLC or a force-close. We should expose that info.

### PR DESCRIPTION
**Pull request by dunxen**
This PR supersedes #2618 and includes a fix for #2738.

After this PR is merged, #2476 should be included again (it had been reverted prior to a previous release).

From 2618:

> When the user is fetching their current balances after forwarding a payment (before it clears), they'll see a
MaybePreimageClaimableHTLC and a MaybeTimeoutClaimableHTLC but if they sum up their balance using
Balance::claimable_amount_satoshis neither will be included.
>
> Obviously, exactly one of the two balances should be included - one of the two resolutions should happen in our favor. This causes our visible balance to fluctuate up and down by the full value of any HTLCs we're in the middle of forwarding, which is incredibly confusing to see. If we want to stop the fluctuations, we need to pick one of the two balances to include. The obvious candidate is MaybeTimeoutClaimableHTLC as it is the lower of the two, and represents our balance without the fee we'd receive from the forward.
>
> Sadly, if we always include it, we'll end up also including any HTLCs which we've sent but which haven't yet been claimed by their recipient, which is the wrong behavior.
>
> Luckily, we have access to the Option<HTLCSource> while walking HTLCs, which allows us to add an outbound_payment flag to MaybeTimeoutClaimableHTLC. This allows us to only include forwarded payments in claimable_amount_satoshis.
>
> Sadly, even with this in place our balance still fluctuates by the
changes in the commitment transaction fees we have to pay during
forwarding, but addressing that is left for later.

Fixes #2738.

### CODE REVIEW

File: lightning/src/chain/channelmonitor.rs [hunk 1]
```diff
@@ -906,6 +913,10 @@ pub(crate) struct ChannelMonitorImpl<Signer: EcdsaChannelSigner> {
 	// of block connection between ChannelMonitors and the ChannelManager.
 	funding_spend_seen: bool,
 
+	/// True if the commitment transaction fee is paid by us.
+	/// Added in 0.0.124.
+	holder_pays_commitment_tx_fee: Option<bool>,
```
[the remark this answers is not in the document]
Comment (dunxen) [reply lightning/src/chain/channelmonitor.rs:971]: Nah, it doesn't change in any way for the commitment tx fees. This still applies:

> Since the fees are currently one-sided (the party which requested the channel creation always pays the fees for the commitment transaction), it's simplest to only allow it to set fee levels; however, as the same fee rate applies to HTLC transactions, the receiving node must also care about the reasonableness of the fee.

https://github.com/lightning/bolts/blob/master/02-peer-protocol.md#rationale-25

File: lightning/src/chain/channelmonitor.rs [hunk 2]
```diff
@@ -635,25 +635,35 @@ pub enum Balance {
...
 		/// with their [`Balance::MaybeTimeoutClaimableHTLC::outbound_payment`] flag *not* set, as
 		/// well as any dust HTLCs which would otherwise be represented the same.
+		///
+		/// This amount (rounded up to a whole satoshi value) will not be included in `amount_satoshis`.
 		outbound_forwarded_htlc_rounded_msat: u64,
 		/// The amount of millisatoshis which has been burned to fees from HTLCs which are inbound
 		/// to us and for which we know the preimage. This is the sum of the millisatoshis part of
 		/// all HTLCs which would be represented by [`Balance::ContentiousClaimable`] on channel
-		/// close, but who's current value is included in
+		/// close, but whose current value is included in
```
Comment (valentinewallace) [inline lightning/src/chain/channelmonitor.rs:667]: nit: this fix belongs in the previous commit that added this doc

File: lightning/src/chain/channelmonitor.rs [hunk 3]
```diff
@@ -2391,12 +2401,13 @@ impl<Signer: EcdsaChannelSigner> ChannelMonitor<Signer> {
 					}
 				}
 			}
+			let tx_fee_satoshis = chan_utils::commit_tx_fee_sat(
```
Comment (valentinewallace) [inline lightning/src/chain/channelmonitor.rs:2429]: This seems unrelated to this commit?

File: lightning/src/chain/channelmonitor.rs [hunk 4]
```diff
@@ -635,25 +635,35 @@ pub enum Balance {
...
+		/// `amount_satoshis` or equivalent thereof.
 		inbound_claiming_htlc_rounded_msat: u64,
 		/// The amount of millisatoshis which has been burned to fees from HTLCs which are inbound
 		/// to us and for which we do not know the preimage. This is the sum of the millisatoshis
 		/// part of all HTLCs which would be represented by [`Balance::MaybePreimageClaimableHTLC`]
 		/// on channel close, as well as any dust HTLCs which would otherwise be represented the
 		/// same.
+		///
+		/// This amount (rounded up to a whole satoshi value) will not be included in the counterparty's
+		/// `amount_satoshis` or equivalent thereof.
```
Comment (valentinewallace) [inline lightning/src/chain/channelmonitor.rs:681]: What does "or equivalent thereof" refer to?

File: lightning/src/chain/channelmonitor.rs [hunk 5]
```diff
@@ -2331,6 +2354,7 @@ impl<Signer: EcdsaChannelSigner> ChannelMonitor<Signer> {
 						res.push(Balance::ClaimableAwaitingConfirmations {
 							amount_satoshis: prev_commitment.to_self_value_sat,
 							confirmation_height: conf_thresh,
+							source: BalanceSource::CounterpartyForceClosed,
```
Comment (valentinewallace) [inline lightning/src/chain/channelmonitor.rs:2357]: Should this be `HolderForceClosed`? Seems that we're comparing the txid to our previous holder commitment tx.

File: lightning/src/chain/channelmonitor.rs (hunk 4 above)
Comment (dunxen) [reply lightning/src/chain/channelmonitor.rs:681]: I suppose it's not worth adding that part to refer to whatever other implementations call that. Will remove.

File: lightning/src/chain/channelmonitor.rs (hunk 5 above)
Comment (dunxen) [reply lightning/src/chain/channelmonitor.rs:2357]: This is true. I did misinterpret that field name and didn't check the comments.

**Review by valentinewallace — APPROVED** [review]
