### PR TITLE
Static invoice server: treat forwarded invoice requests as onion message forwards 

### LINKED ISSUE #4110: Fix forwarding OMs to OM-mailbox clients when sending a fallback invoice_request for a static invoice
https://github.com/lightningdevkit/rust-lightning/pull/4049#discussion_r2349355295

### LINKED ISSUE #4112: LSP onionessage send to offline client will fail
Imagine an LSP with a mobile client. The LSP wants to pay an offer that client issued. It generates an onion messages invreq and sends it. The OnionMessenger notices it's not connected and searches the network graph. It doesn't find the mobile client so doesn't create a direct connect event. The message gets dropped and the payment fails.

We should probably just generate the DC event irrespective of the network graph so the LSP can use LSPS5 to wake the client.

### PR DESCRIPTION
**Pull request by valentinewallace**
Previously, when a static invoice server forwarded an invoice request to an
often-offline recipient, they would treat the outbound message like any other
outbound onion message initiated by their own node. That means they would
buffer the onion message internally in the onion messenger and generate a
`ConnectionNeeded` event if the next-hop node was offline.

Buffering the onion message in this case poses a DoS risk for the invoice
server node, since they do not control the quantity of invoice requests they
receive on behalf of often-offline recipients. Instead, we should treat these
forwarded invoice requests like any other onion message that needs to be
forwarded -- if the next-hop node is offline, either drop the message or
generate an `OnionMessageIntercepted` event for it (pushing the DoS management
onto the handler of the interception event).

Closes #4110 

Also closes #4112:

Imagine an LSP with a mobile client. The LSP wants to pay an offer that client
issued. It generates an onion messages invreq and sends it. The OnionMessenger
notices it's not connected and searches the network graph. It doesn't find the
mobile client so doesn't create a direct connect event. The message gets
dropped and the payment fails.

Here we start generating the DC event irrespective of the network graph so the
LSP can use LSPS5 to wake the client.

### CODE REVIEW

File: lightning/src/events/mod.rs [hunk 1]
```diff
@@ -1617,6 +1617,9 @@ pub enum Event {
 	/// `OnionMessenger` was initialized with
 	/// [`OnionMessenger::new_with_offline_peer_interception`], see its docs.
 	///
+	/// If LSPS5 is supported by this node, it should be used on receipt of this event to wake up the
```
Comment (TheBlueMatt) [inline lightning/src/events/mod.rs]: nit: I dont think we need to restrict this to LSPS5, just a general note that the client should be woken if possible, eg via LSPS5.

File: lightning/src/events/mod.rs [hunk 2]
```diff
@@ -1661,6 +1664,14 @@ pub enum Event {
 		/// recipient is online to provide a new invoice. This path should be persisted and
 		/// later provided to [`ChannelManager::respond_to_static_invoice_request`].
 		///
+		/// This path's [`BlindedMessagePath::introduction_node`] MUST be set to our node or one of our
```
Comment (TheBlueMatt) [inline lightning/src/events/mod.rs:1669]: Shouldn't this be documented on the client end of the protocol not the server end?

File: lightning/src/onion_message/messenger.rs [hunk 3]
```diff
@@ -490,6 +490,15 @@ pub enum MessageSendInstructions {
...
 		instructions: ResponseInstruction,
 	},
+	/// Indicates that this onion message did not originate from our node and is being forwarded
+	/// through us from another node on the network to the destination.
+	ForwardedMessage {
+		/// The destination where we need to send the forwarded onion message.
+		destination: Destination,
+		/// The reply path which should be included in the message, that terminates at the original
+		/// sender of this forwarded message.
+		reply_path: BlindedMessagePath,
```
Comment (TheBlueMatt) [inline lightning/src/onion_message/messenger.rs]: This can be an `Option`, no?

File: lightning/src/onion_message/messenger.rs [hunk 4]
```diff
@@ -490,6 +490,15 @@ pub enum MessageSendInstructions {
 		/// The instructions provided by the [`Responder`].
 		instructions: ResponseInstruction,
 	},
+	/// Indicates that this onion message did not originate from our node and is being forwarded
+	/// through us from another node on the network to the destination.
```
Comment (TheBlueMatt) [inline lightning/src/onion_message/messenger.rs:494]: More information on why this should be used and why its separate would be nice. Something about the difference in DoS handling.

File: lightning/src/onion_message/messenger.rs [hunk 5]
```diff
@@ -1492,12 +1503,38 @@ where
 			} => (destination, None),
 		};
 
-		let mut logger = WithContext::from(&self.logger, None, None, None);
-		let result = self.find_path(destination).and_then(|path| {
-			let first_hop = path.intermediate_nodes.get(0).map(|p| *p);
-			logger = WithContext::from(&self.logger, first_hop, None, None);
-			self.enqueue_onion_message(path, contents, reply_path, log_suffix)
-		});
+		let path = self.find_path(destination).map_err(|e| {
```
Comment (TheBlueMatt) [inline lightning/src/onion_message/messenger.rs]: Should we avoid calling `find_path` in the forwarded case and just require it be a peer?

File: lightning/src/events/mod.rs (hunk 2 above)
Comment (valentinewallace) [reply lightning/src/events/mod.rs:1669]: I generally agree, though the only other possible place I see is on the `ServeStaticInvoice` onion message field where no one will see it. Maybe that's fine? There's nothing clients can do in practice to satisfy this requirement right now anyway since LDK generates the path without their intervention, so I guess I'll move it. 

Edit: basically duplicated the docs in both places so they are more likely to be surfaced

File: lightning/src/onion_message/messenger.rs [hunk 6]
```diff
@@ -689,14 +689,20 @@ where
...
-				{
-					let first_node_addresses = Some(addresses.to_vec());
+				Some((features, addresses)) if features.supports_onion_messages() => {
 					Ok(OnionMessagePath {
 						intermediate_nodes: vec![],
 						destination,
-						first_node_addresses,
+						first_node_addresses: addresses.to_vec(),
+					})
+				},
```
Comment (valentinewallace) [inline lightning/src/onion_message/messenger.rs]: Maybe we should not do this new always-generate-DC-event behavior if the node is announced, actually?

File: lightning/src/onion_message/messenger.rs [hunk 7]
```diff
@@ -362,10 +362,7 @@ impl OnionMessageRecipient {
 	fn dequeue_message(&mut self) -> Option<OnionMessage> {
 		let pending_messages = match self {
 			OnionMessageRecipient::ConnectedPeer(pending_messages) => pending_messages,
-			OnionMessageRecipient::PendingConnection(pending_messages, _, _) => {
-				debug_assert!(false);
```
Comment (TheBlueMatt) [inline lightning/src/onion_message/messenger.rs:366]: I don't see why this was a bug? We call `dequeue_message` to fetch messages for sending to a peer, which is called by the `PeerManager` for connected peers. We shouldn't ever have that method be called for a disconnected peer, if we do it indicates a bug in `PeerManager` (or the test in question).

File: lightning/src/onion_message/messenger.rs (hunk 6 above)
Comment (TheBlueMatt) [reply lightning/src/onion_message/messenger.rs]: You mean `announced && !supports_onion_messages`? That seems reasonable. Otherwise we could even drop the `supports_onion_messages` check now, seems weird to generate the DC event for a peer that doesn't support OMs and just drop the connection addresses lol.

Comment (valentinewallace) [reply lightning/src/onion_message/messenger.rs]: I didn't follow that -- how can we drop the OM feature check but also avoid generating DC events for non-OM-supporting peers? I pushed what I think is correct.
