### PR TITLE
Fix some onion errors and assert their length is correct

### LINKED ISSUE #1879: Ensure UPDATE errors have an update
cc https://github.com/lightningdevkit/rust-lightning/pull/1835#discussion_r1034148005

### PR DESCRIPTION
**Pull request by TheBlueMatt**
When we're constructing an HTLCFailReason, we should check that we
set the data to at least the correct length for the given failure
code, which we do here.

First we move HTLCFailReason into `onion_utils` and encapsulate it a bit better, making channelmanager just a bit smaller. Then we can assert the length, but only after fixing a few issues.

Fixes #1879 but I'm frankly a bit confused - I don't see the `14` @valentinewallace claimed was being used incorrectly in phantom failures - maybe it was already fixed?

### CODE REVIEW

**Comment by valentinewallace** [comment]
I think this was it, so `| 13`: https://github.com/lightningdevkit/rust-lightning/blob/main/lightning/src/ln/channelmanager.rs#L2301. That scope will also set `chan_update_opt` to `None`, would have to check if any of the expiry checks below are reachable for phantom payments

File: lightning/src/ln/channelmanager.rs [hunk 1]
```diff
@@ -326,6 +326,26 @@ impl HTLCFailReason {
 			}
 		}
 	}
+
+	fn decode_onion_failure<T: secp256k1::Signing, L: Deref>(&self, secp_ctx: &Secp256k1<T>, logger: &L, htlc_source: &HTLCSource) -> (Option<crate::routing::gossip::NetworkUpdate>, Option<u64>, bool, Option<u16>, Option<Vec<u8>>) where L::Target: Logger {
```
Comment (valentinewallace) [inline lightning/src/ln/channelmanager.rs]: Could we wrap this at roughly 100?

File: lightning/src/ln/channelmanager.rs [hunk 2]
```diff
@@ -49,6 +49,7 @@ use crate::ln::features::InvoiceFeatures;
 use crate::routing::router::{InFlightHtlcs, PaymentParameters, Route, RouteHop, RoutePath, RouteParameters};
 use crate::ln::msgs;
 use crate::ln::onion_utils;
+use crate::ln::onion_utils::HTLCFailReason;
```
Comment (valentinewallace) [inline lightning/src/ln/channelmanager.rs:52]: nit:
```suggestion
use crate::ln::onion_utils::{self, HTLCFailReason};
```

File: lightning/src/ln/onion_utils.rs [hunk 3]
```diff
@@ -592,6 +592,143 @@ pub(super) fn process_onion_failure<T: secp256k1::Signing, L: Deref>(secp_ctx: &
...
+	}
+}
+
+impl Writeable for HTLCFailReason {
+	fn write<W: crate::util::ser::Writer>(&self, writer: &mut W) -> Result<(), crate::io::Error> {
+		self.0.write(writer)
+	}
+}
+impl Readable for HTLCFailReason {
+	fn read<R: crate::io::Read>(reader: &mut R) -> Result<Self, crate::ln::msgs::DecodeError> {
```
Comment (valentinewallace) [inline lightning/src/ln/onion_utils.rs:628]: nit: 
```suggestion
	fn read<R: Read>(reader: &mut R) -> Result<Self, msgs::DecodeError> {
```

File: lightning/src/ln/onion_utils.rs [hunk 4]
```diff
@@ -592,6 +592,143 @@ pub(super) fn process_onion_failure<T: secp256k1::Signing, L: Deref>(secp_ctx: &
...
+			},
+			HTLCFailReasonRepr::LightningError { .. } => {
+				write!(f, "pre-built LightningError")
+			}
+		}
+	}
+}
+
+impl Writeable for HTLCFailReason {
+	fn write<W: crate::util::ser::Writer>(&self, writer: &mut W) -> Result<(), crate::io::Error> {
```
Comment (valentinewallace) [inline lightning/src/ln/onion_utils.rs:623]: nit: import `Writer`

File: lightning/src/ln/channelmanager.rs [hunk 5]
```diff
@@ -2042,10 +2042,13 @@ impl<M: Deref, T: Deref, K: Deref, F: Deref, L: Deref> ChannelManager<M, T, K, F
 		// Also, ensure that, in the case of an unknown preimage for the received payment hash, our
 		// payment logic has enough time to fail the HTLC backward before our onchain logic triggers a
 		// channel closure (see HTLC_FAIL_BACK_BUFFER rationale).
-		if (hop_data.outgoing_cltv_value as u64) <= self.best_block.read().unwrap().height() as u64 + HTLC_FAIL_BACK_BUFFER as u64 + 1	{
+		let current_height: u32 = self.best_block.read().unwrap().height();
+		if (hop_data.outgoing_cltv_value as u64) <= current_height as u64 + HTLC_FAIL_BACK_BUFFER as u64 + 1 {
+			let mut err_data = Vec::with_capacity(12);
+			err_data.extend_from_slice(&amt_msat.to_be_bytes());
+			err_data.extend_from_slice(&current_height.to_be_bytes());
```
Comment (valentinewallace) [inline lightning/src/ln/channelmanager.rs:2049]: It would be nice if this were made consistent with the other places we construct `0x4000 | 15`, which currently use `byte_utils`

File: lightning/src/ln/onion_utils.rs [hunk 6]
```diff
@@ -592,6 +592,92 @@ pub(super) fn process_onion_failure<T: secp256k1::Signing, L: Deref>(secp_ctx: &
...
+				process_onion_failure(secp_ctx, logger, &htlc_source, err.data.clone())
+			},
+			HTLCFailReason::Reason { ref failure_code, ref data, .. } => {
+				// we get a fail_malformed_htlc from the first hop
+				// TODO: We'd like to generate a NetworkUpdate for temporary
+				// failures here, but that would be insufficient as find_route
+				// generally ignores its view of our own channels as we provide them via
+				// ChannelDetails.
+				// TODO: For non-temporary failures, we really should be closing the
+				// channel here as we apparently can't relay through them anyway.
```
Comment (valentinewallace) [inline lightning/src/ln/onion_utils.rs:723]: Do these comments still make sense here, or should they stay in `fail_backwards_internal`?

File: lightning/src/ln/channelmanager.rs (hunk 5 above)
Comment (valentinewallace) [reply lightning/src/ln/channelmanager.rs:2049]: I meant it would be nice to fix the other callsites, but it's pre-existing so not a big deal

**Comment by valentinewallace** [comment]
This test hits one of the new debug panics in `HTLCFailReason::reason`: 
```
#[test]
fn test_phantom_failure_expires_too_soon() {
	// Test that we fail back phantoms if the upstream node fiddled with the CLTV too much with the
	// correct error code.
	let chanmon_cfgs = create_chanmon_cfgs(2);
	let node_cfgs = create_node_cfgs(2, &chanmon_cfgs);
	let node_chanmgrs = create_node_chanmgrs(2, &node_cfgs, &[None, None]);
	let nodes = create_network(2, &node_cfgs, &node_chanmgrs);

	let channel = create_announced_chan_between_nodes(&nodes, 0, 1, channelmanager::provided_init_features(), channelmanager::provided_init_features());

	// Get the route.
	let recv_value_msat = 10_000;
	let (_, payment_hash, payment_secret) = get_payment_preimage_hash!(nodes[1], Some(recv_value_msat));
	let (mut route, phantom_scid) = get_phantom_route!(nodes, recv_value_msat, channel);

	// Route the HTLC through to the destination.
	nodes[0].node.send_payment(&route, payment_hash, &Some(payment_secret), PaymentId(payment_hash.0)).unwrap();
	check_added_monitors!(nodes[0], 1);
	let update_0 = get_htlc_update_msgs!(nodes[0], nodes[1].node.get_our_node_id());
	let mut update_add = update_0.update_add_htlcs[0].clone();

	// Modify the route to have a too-low cltv.
	// update_add.cltv_expiry += CLTV_FAR_FAR_AWAY;

	connect_blocks(&nodes[1], 72);
	nodes[1].node.handle_update_add_htlc(&nodes[0].node.get_our_node_id(), &update_add);
	commitment_signed_dance!(nodes[1], nodes[0], &update_0.commitment_signed, false, true);

	let update_1 = get_htlc_update_msgs!(nodes[1], nodes[0].node.get_our_node_id());
	assert!(update_1.update_fail_htlcs.len() == 1);
	let fail_msg = update_1.update_fail_htlcs[0].clone();
	nodes[0].node.handle_update_fail_htlc(&nodes[1].node.get_our_node_id(), &fail_msg);
	commitment_signed_dance!(nodes[0], nodes[1], update_1.commitment_signed, false);

	// Ensure the payment fails with the expected error.
	let mut fail_conditions = PaymentFailedConditions::new()
		.blamed_scid(phantom_scid)
		.expected_htlc_error_data(0x1000 | 14, &[]);
		expect_payment_failed_conditions(&nodes[0], payment_hash, false, fail_conditions);
}
```
I think the other phantom `0x1000|14` error would hit the panic as well. I guess the lack of test coverage here is on me 😅

File: lightning/src/ln/onion_utils.rs [hunk 7]
```diff
@@ -592,6 +592,145 @@ pub(super) fn process_onion_failure<T: secp256k1::Signing, L: Deref>(secp_ctx: &
...
+			},
+			HTLCFailReasonRepr::LightningError { ref err } => {
+				encrypt_failure_packet(incoming_packet_shared_secret, &err.data)
+			}
+		}
+	}
+
+	pub(super) fn decode_onion_failure<T: secp256k1::Signing, L: Deref>(
+		&self, secp_ctx: &Secp256k1<T>, logger: &L, htlc_source: &HTLCSource
+	) -> (Option<crate::routing::gossip::NetworkUpdate>, Option<u64>, bool, Option<u16>, Option<Vec<u8>>)
```
Comment (valentinewallace) [inline lightning/src/ln/onion_utils.rs:714]: nit: `NetworkUpdate` is imported already

File: lightning/src/ln/onion_utils.rs [hunk 8]
```diff
@@ -592,6 +592,145 @@ pub(super) fn process_onion_failure<T: secp256k1::Signing, L: Deref>(secp_ctx: &
...
+			},
+			HTLCFailReasonRepr::Reason { ref failure_code, ref data, .. } => {
+				// we get a fail_malformed_htlc from the first hop
+				// TODO: We'd like to generate a NetworkUpdate for temporary
+				// failures here, but that would be insufficient as find_route
+				// generally ignores its view of our own channels as we provide them via
+				// ChannelDetails.
+				if let &HTLCSource::OutboundRoute { ref path, .. } = htlc_source {
+					(None, Some(path.first().unwrap().short_channel_id), true, Some(*failure_code), Some(data.clone()))
+				} else { unreachable!(); }
```
Comment (valentinewallace) [inline lightning/src/ln/onion_utils.rs:728]: It'd remove some `unreachable`s to make `HTLCSource::OutboundRoute` have an inner struct, but I think that'd be a future consideration

**Review by valentinewallace — COMMENTED** [review]
Really nice cleanup, basically LGTM

**Review by valentinewallace — COMMENTED** [review]
LGTM after squash
