### PR TITLE
Sanity check for ChannelManager and KeysInterface

### LINKED ISSUE #1174: Sanity Check KeysInterface on ChannelManager Deserialization
If the KeysInterface provided to the ChannelManager is generating different keys from what we had before being written, we need to fail, not try to run.

### PR DESCRIPTION
**Pull request by vss96**
This fixes #1174.

### CODE REVIEW

File: lightning/src/chain/keysinterface.rs [hunk 1]
```diff
@@ -571,6 +573,8 @@ impl InMemorySigner {
 		let sighash = hash_to_message!(&bip143::SigHashCache::new(spend_tx).signature_hash(input_idx, &witness_script, descriptor.output.value, SigHashType::All)[..]);
 		let local_delayedsig = secp_ctx.sign(&sighash, &delayed_payment_key);
 
+		if descriptor.output.script_pubkey != witness_script { return Err(()); }
```
Comment (TheBlueMatt) [inline lightning/src/chain/keysinterface.rs:576]: The `witness_script `is the hash preimage of the segwit output. You can create the correct script with `Address::p2wsh`.

File: lightning/src/chain/keysinterface.rs [hunk 2]
```diff
@@ -541,6 +541,8 @@ impl InMemorySigner {
 		let sighash = hash_to_message!(&bip143::SigHashCache::new(spend_tx).signature_hash(input_idx, &witness_script, descriptor.output.value, SigHashType::All)[..]);
 		let remotesig = secp_ctx.sign(&sighash, &self.payment_key);
 
+		if descriptor.output.script_pubkey != witness_script { return Err(()); }
```
Comment (TheBlueMatt) [inline lightning/src/chain/keysinterface.rs:544]: The witness script here is different from the output. You need to create a second address with `Address::p2wpkh` to compare against instead.

**Review by TheBlueMatt — COMMENTED** [review]
Thanks!

While you're here, can you also add a similar script check in `KeysManager::spend_spendable_outputs` in the second for loop in the `SpendableOutputDescriptor::StaticOutput` match variant?

**Comment by vss96** [comment]
> While you're here, can you also add a similar script check in KeysManager::spend_spendable_outputs in the second for loop in the SpendableOutputDescriptor::StaticOutput match variant?

@TheBlueMatt Initially, there is a check for the output's script_pubkey and either 1 or 2 is assigned to the derivation_idx.
 If the scripts are not equal, do we panic! at that spot?
And if they are equal do we assign derivation_idx=1 and continue?

File: lightning/src/chain/keysinterface.rs (hunk 1 above)
Comment (vss96) [reply lightning/src/chain/keysinterface.rs]: Just to be sure, which Network am I supposed to use for the p2wsh method?

File: lightning/src/chain/keysinterface.rs [hunk 3]
```diff
@@ -540,6 +540,10 @@ impl InMemorySigner {
 		let witness_script = bitcoin::Address::p2pkh(&::bitcoin::PublicKey{compressed: true, key: remotepubkey}, Network::Testnet).script_pubkey();
 		let sighash = hash_to_message!(&bip143::SigHashCache::new(spend_tx).signature_hash(input_idx, &witness_script, descriptor.output.value, SigHashType::All)[..]);
 		let remotesig = secp_ctx.sign(&sighash, &self.payment_key);
+		let network = bitcoin::Network::Bitcoin;
+		let payment_script = bitcoin::Address::p2wsh(&witness_script, network).script_pubkey();
```
Comment (TheBlueMatt) [inline lightning/src/chain/keysinterface.rs:544]: I believe this needs to be a p2wpkh instead of p2wsh

File: lightning/src/chain/keysinterface.rs (hunk 1 above)
Comment (TheBlueMatt) [reply lightning/src/chain/keysinterface.rs]: Network wont matter - the network only changes the address, once we call `script_pubkey()` we've forgotten the network information again.

**Comment by vss96** [comment]
@TheBlueMatt  I created the script from segwit script hash for spendable_outputs:
```rust					
let payment_script = bitcoin::Address::p2wsh(&witness_script, Network::Testnet).script_pubkey();
assert_eq!(payment_script, output.script_pubkey);
```
I ran the tests locally and they seem to be failing. Maybe I'm doing something wrong?

**Comment by TheBlueMatt** [comment]
> let payment_script = bitcoin::Address::p2wsh(&witness_script, Network::Testnet).script_pubkey();

This should also be a p2wpkh, not p2wsh.

**Comment by vss96** [comment]
@TheBlueMatt I'm done with the changes for the pr but I'm facing issues with squashing the commits 😭

**Comment by TheBlueMatt** [comment]
The Bitcoin Core docs have some discussion of how to do it at https://github.com/bitcoin/bitcoin/blob/master/doc/productivity.md

**Comment by vss96** [comment]
@TheBlueMatt I was trying to rebase and squash the 6 commits but by the time I'm done with it, the branch is behind by like 390 commits and when I force push I see a lot of other changes.

**Comment by TheBlueMatt** [comment]
You shouldn't need to rebase unless there is a conflict (there currently is not). If you're using rebase, it may be simplest to rebase on top of `34cdca91baa`, which is the current commit this is based on.

**Comment by vss96** [comment]
That worked! I was trying to do `git rebase -i HEAD~6` and that included the merged commits as well and was causing some issues.

File: lightning/src/chain/keysinterface.rs [hunk 4]
```diff
@@ -1029,6 +1035,8 @@ impl KeysManager {
 						assert_eq!(pubkey.key, self.shutdown_pubkey);
 					}
 					let witness_script = bitcoin::Address::p2pkh(&pubkey, Network::Testnet).script_pubkey();
+					let payment_script = bitcoin::Address::p2wpkh(&pubkey, Network::Testnet).expect("uncompressed key found").script_pubkey();
+					assert_eq!(payment_script, output.script_pubkey);
```
Comment (TheBlueMatt) [inline lightning/src/chain/keysinterface.rs:1039]: Lets not assert here, instead returning an error.

**Review by TheBlueMatt — DISMISSED** [review]

File: lightning/src/chain/keysinterface.rs [hunk 5]
```diff
@@ -540,6 +540,9 @@ impl InMemorySigner {
 		let witness_script = bitcoin::Address::p2pkh(&::bitcoin::PublicKey{compressed: true, key: remotepubkey}, Network::Testnet).script_pubkey();
 		let sighash = hash_to_message!(&bip143::SigHashCache::new(spend_tx).signature_hash(input_idx, &witness_script, descriptor.output.value, SigHashType::All)[..]);
 		let remotesig = secp_ctx.sign(&sighash, &self.payment_key);
+		let payment_script = bitcoin::Address::p2wpkh(&::bitcoin::PublicKey{compressed: true, key: remotepubkey}, Network::Bitcoin).unwrap().script_pubkey();
```
Comment (valentinewallace) [inline lightning/src/chain/keysinterface.rs:543]: All three of these updated methods document which errors they return, do any of them need updating?

**Review by valentinewallace — DISMISSED** [review]

File: lightning/src/chain/keysinterface.rs (hunk 5 above)
Comment (vss96) [reply lightning/src/chain/keysinterface.rs:543]: It looks like all 3 methods have docs specifically stating under what conditions errors are returned, so I'll need to update all 3.

**Comment by vss96** [comment]
@TheBlueMatt Valentine had pointed out how the docs for the methods in keysinterface mention the conditions under which Err is returned, so I went ahead and updated them.

**Review by valentinewallace — APPROVED** [review]
Thanks for the docs updates!

File: lightning/src/chain/keysinterface.rs [hunk 6]
```diff
@@ -927,8 +935,9 @@ impl KeysManager {
 	/// output to the given change destination (if sufficient change value remains). The
 	/// transaction will have a feerate, at least, of the given value.
 	///
-	/// Returns `Err(())` if the output value is greater than the input value minus required fee or
-	/// if a descriptor was duplicated.
+	/// Returns `Err(())` if the output value is greater than the input value minus required fee,
+	/// if a descriptor was duplicated, or if p2wpkh script does not 
+	/// match the descriptor output script.
```
Comment (TheBlueMatt) [inline lightning/src/chain/keysinterface.rs:940]: Ah, we should probably update the body to stop unwrap'ing the other spend calls, then update the doc here to just say something like the generic text I pasted above.

**Review by TheBlueMatt — APPROVED** [review]
Thanks!

**Review by valentinewallace — APPROVED** [review]
