### PR TITLE
Avoid generating unpayable routes due to balance restrictions

### LINKED ISSUE #1126: `ChannelDetails::outbound_capacity_msat` needs to be more exact
I had an issue locally where I'd be stuck unable to send a payment because the router kept selecting a channel and use all of the availability listed as `outbound_capacity_msat` before adding other MPP hops. However, `outbound_capacity_msat` isn't exact, and slightly over-counts the amount we can reasonably send (as documented, and ignored in `get_route`). This resulted in an un-sendable payment. The sample gave me this:

```
ERROR: failed to send payment: PartialFailure([Err(Cannot send value that would put our balance under counterparty-announced channel reserve value (30000000)), Ok(()), Err(Cannot send value that would not leave enough to pay for fees. Pending value to self: 38978302. local_commit_tx_fee 1656000)])
```

### LINKED ISSUE #2252: Add a `next_outbound_htlc_minimum_msat` to `ChannelDetails`
Similar to #1126 but the opposite direction - when we hit the dust exposure threshold we may be unable to send more dust HTLCs on a channel but can happily send larger value HTLCs. To feed this info to the router we should add an htlc min field to channeldetails, and make sure the router logs appropriately (or even gives a different error message!) when we cant find a route due to hitting this.

### PR DESCRIPTION
**Pull request by TheBlueMatt**
When calculating the amount available to send for the next HTLC, if
we over-count we may create routes which are not actually usable.
    
Historically this has been an issue, constructing routes that aren't payable and leading to spurious payment failures.

Here we fix that issue across several commits, ultimately removing the entire can-we-send complexity in `send_htlc` entirely.

Fixes #1126.
Fixes #2252.

### CODE REVIEW

File: lightning/src/ln/channel.rs [hunk 1]
```diff
@@ -5857,14 +5857,13 @@ impl<Signer: WriteableEcdsaChannelSigner> Channel<Signer> {
...
-		let keys = self.build_holder_transaction_keys(self.cur_holder_commitment_transaction_number);
-		let commitment_stats = self.build_commitment_transaction(self.cur_holder_commitment_transaction_number, &keys, true, true, logger);
 		if !self.is_outbound() {
 			// Check that we won't violate the remote channel reserve by adding this HTLC.
 			let htlc_candidate = HTLCCandidate::new(amount_msat, HTLCInitiator::LocalOffered);
 			let counterparty_commit_tx_fee_msat = self.next_remote_commit_tx_fee_msat(htlc_candidate, None);
 			let holder_selected_chan_reserve_msat = self.holder_selected_channel_reserve_satoshis * 1000;
-			if commitment_stats.remote_balance_msat < counterparty_commit_tx_fee_msat + holder_selected_chan_reserve_msat {
+			let remote_balance_msat = (self.channel_value_satoshis * 1000 - self.value_to_self_msat).saturating_sub(inbound_stats.pending_htlcs_value_msat);
+			if remote_balance_msat < counterparty_commit_tx_fee_msat + holder_selected_chan_reserve_msat {
```
Comment (dunxen) [inline lightning/src/ln/channel.rs]: So the only reason this could ever be true is if adding the outbound HTLC increased the fees for the counterparty commitment tx too much? Don't know why I got so tripped up here

Comment (dunxen) [reply lightning/src/ln/channel.rs]: Oops. Outdated. Doc improvements cleared that up.

File: lightning/src/ln/channel.rs [hunk 2]
```diff
@@ -2686,21 +2689,121 @@ impl<Signer: WriteableEcdsaChannelSigner> Channel<Signer> {
...
+				available_capacity_msat = cmp::max(0, cmp::min(capacity_minus_commitment_fee_msat, available_capacity_msat as i64)) as u64;
+			} else {
+				available_capacity_msat = capacity_minus_commitment_fee_msat as u64;
+			}
+		} else {
+			// If the channel is inbound (i.e. counterparty pays the fee), we need to make sure
+			// sending a new HTLC won't reduce their balance below our dust threshold.
+			let mut real_dust_limit_success_sat = self.counterparty_dust_limit_satoshis;
+			if !self.opt_anchors() {
+				real_dust_limit_success_sat += self.feerate_per_kw as u64 * htlc_success_tx_weight(false) / 1000;
```
Comment (dunxen) [inline lightning/src/ln/channel.rs:2735]: Are we always using the better zero-fee HTLC tx variant of anchors? Is that the reason why we only add this HTLC tx fee when anchors aren't negotiated?

File: lightning/src/ln/channel.rs [hunk 3]
```diff
@@ -2686,21 +2689,121 @@ impl<Signer: WriteableEcdsaChannelSigner> Channel<Signer> {
...
+			remaining_msat_below_dust_exposure_limit =
+				Some(self.get_max_dust_htlc_exposure_msat().saturating_sub(on_counterparty_dust_htlc_exposure_msat));
+			dust_exposure_dust_limit_msat = cmp::max(dust_exposure_dust_limit_msat, htlc_success_dust_limit * 1000);
+		}
+
+		let on_holder_dust_htlc_exposure_msat = inbound_stats.on_holder_tx_dust_exposure_msat + outbound_stats.on_holder_tx_dust_exposure_msat;
+		if on_holder_dust_htlc_exposure_msat as i64 + htlc_timeout_dust_limit as i64 * 1000 - 1 > self.get_max_dust_htlc_exposure_msat() as i64 {
+			remaining_msat_below_dust_exposure_limit = Some(cmp::max(
+				remaining_msat_below_dust_exposure_limit.unwrap_or(0),
+				self.get_max_dust_htlc_exposure_msat().saturating_sub(on_holder_dust_htlc_exposure_msat)));
```
Comment (alecchendev) [inline lightning/src/ln/channel.rs:2779]: I might be getting things confused, but shouldn't this be the min between the two? I'm thinking if `remaining_msat_below_dust_exposure_limit` represents that we only have at most this many msat to send (regarding the counterparty's tx) before hitting our max dust exposure, if the most we could send before hitting our max dust exposure regarding the holder's tx is smaller, then we'd want to tell the user they could only send that much?

File: lightning/src/ln/channel.rs [hunk 4]
```diff
@@ -2686,21 +2689,121 @@ impl<Signer: WriteableEcdsaChannelSigner> Channel<Signer> {
...
+		let mut remaining_msat_below_dust_exposure_limit = None;
+		let mut dust_exposure_dust_limit_msat = 0;
+
+		let (htlc_success_dust_limit, htlc_timeout_dust_limit) = if self.opt_anchors() {
+			(self.counterparty_dust_limit_satoshis, self.holder_dust_limit_satoshis)
+		} else {
+			let dust_buffer_feerate = self.get_dust_buffer_feerate(None) as u64;
+			(self.counterparty_dust_limit_satoshis + dust_buffer_feerate * htlc_success_tx_weight(false) / 1000,
+			 self.holder_dust_limit_satoshis       + dust_buffer_feerate * htlc_timeout_tx_weight(false) / 1000)
+		};
```
[the remark this answers is not in the document]
Comment (dunxen) [reply lightning/src/ln/channel.rs:2767]: We only implement the safer zero-fee HTLC tx variant of anchors.

Divide by a thousand because our the dust buffer federate is in terms of kw units

[the remark this answers is not in the document]
Comment (alecchendev) [reply lightning/src/ln/channel.rs:2767]: > We only implement the safer zero-fee HTLC tx variant of anchors.

Ohh gotcha, thanks

> Divide by a thousand because the dust_buffer_feerate is in terms of kw units

Ah my bad I was thinking per_kw as (sats/1000wu) instead of (1000*sats/wu)

**Review by dunxen — APPROVED** [review]
