### PR TITLE
Avoid reusing just-failed channels in the router, making the impossibility penalty configurable

### LINKED ISSUE #1241: Handle only-last-hop temp failure better
Currently if we try to send to a node with a single last-hop hint in the invoice, and the second-to-last node rejects the payment with a temp failure, we'll retry several times through the same channel that we just learned is failed. This is particularly visible on mobile receivers where the receiving device may have gone offline and for some LSPs the payment will just fail again and again.

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Some users want to keep a very long scorer data half-life to maintain knowledge for a longer period of time. Its somewhat unclear if that's optimal, but it is clear that it can cause the scorer to refuse to build a route when the only available channel failed most recently within the halflife. This is rather unexpected behavior, and the fact that the scorer *must* behave this way to avoid #1241 is very annoying in that it prevents fixing this.

Here we move the avoidance of just-failed channels into the router itself, allowing us to make the impossibility penalty configurable, which we do as well.

Closes #1241, superseding #1252.

### CODE REVIEW

**Review by tnull — COMMENTED** [review]
Thanks, generally looks good, just some comments.

File: lightning/src/routing/router.rs [hunk 1]
```diff
@@ -985,15 +992,22 @@ where L::Target: Logger {
...
+					let channel_failed_on_this_payment =
+						payment_params.previously_failed_channels.contains(&short_channel_id);
+
 					// If HTLC minimum is larger than the amount we're going to transfer, we shouldn't
 					// bother considering this channel. If retrying with recommended_value_msat may
 					// allow us to hit the HTLC minimum limit, set htlc_minimum_limit so that we go
 					// around again with a higher amount.
 					if contributes_sufficient_value && doesnt_exceed_max_path_length &&
-						doesnt_exceed_cltv_delta_limit && may_overpay_to_meet_path_minimum_msat {
+						doesnt_exceed_cltv_delta_limit && !channel_failed_on_this_payment &&
```
[the remark this answers is not in the document]
Comment (tnull) [reply lightning/src/routing/router.rs:1003]: Alright, I have no strong opinion on that.

File: lightning/src/routing/router.rs [hunk 2]
```diff
@@ -5482,6 +5498,32 @@ mod tests {
...
+			.with_max_mpp_path_count(1);
+		let keys_manager = test_utils::TestKeysInterface::new(&[0u8; 32], Network::Testnet);
+		let random_seed_bytes = keys_manager.get_secure_random_bytes();
+
+		loop {
+			if let Ok(route) = get_route(&our_id, &payment_params, &network_graph, None, 100, 0, Arc::clone(&logger), &scorer, &random_seed_bytes) {
+				for chan in route.paths[0].iter() {
+					assert!(!payment_params.previously_failed_channels.contains(&chan.short_channel_id));
+				}
+				let victim = (u64::from_ne_bytes(random_seed_bytes[0..8].try_into().unwrap()) as usize)
```
[the remark this answers is not in the document]
Comment (tnull) [reply lightning/src/routing/router.rs:5530]: Ah, right, you're always picking the same position, but since the new route always excludes the previous iteration's victim, this check out. Nevermind then!

File: lightning/src/routing/scoring.rs [hunk 3]
```diff
@@ -374,6 +374,19 @@ pub struct ProbabilisticScoringParameters {
...
 	pub anti_probing_penalty_msat: u64,
+
+	/// This penalty is applied when the amount we're attempting to send over a channel exceeds our
+	/// current estimate of the liquidity available on a channel.
+	///
+	/// Note that in this case the liquidity penalties are still included to ensure such channels
+	/// which may have enough liquidity are scored worse than channels which we do not believe have
+	/// enough.
+	///
+	/// Note if you wish to avoid creating paths with such channels entirely, a penalty of
```
[the remark this answers is not in the document]
Comment (tnull) [reply lightning/src/routing/scoring.rs]: Ah, I think I was misreading the comment. The update version definitely clarifies things.

**Review by tnull — APPROVED** [review]
LGTM

File: lightning/src/routing/scoring.rs [hunk 4]
```diff
@@ -392,6 +392,22 @@ pub struct ProbabilisticScoringParameters {
...
+	/// current estimate of the channel's available liquidity.
+	///
+	/// Note that in this case the [`liquidity_penalty_multiplier_msat`] and
+	/// [`amount_penalty_multiplier_msat`]-based penalties are still included in the overall
+	/// penalty.
+	///
+	/// If you wish to avoid creating paths with such channels entirely, setting this to a value of
+	/// `u64::max_value()` will guarantee that.
+	///
+	/// Default value: 1_0000_0000_000 msat (1 Bitcoin)
```
[the remark this answers is not in the document]
Comment (tnull) [reply lightning/src/routing/scoring.rs:406]: Ah, okay. Is that a common grouping? I memorized "100 M sats", so doing thousands seems more natural to me. As it comes down to a matter of taste, feel free to leave it as is.

File: lightning/src/routing/scoring.rs [hunk 5]
```diff
@@ -2136,11 +2154,11 @@ mod tests {
 		};
 
 		let params = ProbabilisticScoringParameters {
-			liquidity_penalty_multiplier_msat: 40_000,
+			considered_impossible_penalty_msat: 42_420,
 			..ProbabilisticScoringParameters::zero_penalty()
 		};
 		let scorer = ProbabilisticScorer::new(params, &network_graph, &logger);
-		assert_eq!(scorer.channel_penalty_msat(42, &source, &target, usage), 80_000);
+		assert_eq!(scorer.channel_penalty_msat(42, &source, &target, usage), 42_420);
```
Comment (jkczyz) [inline lightning/src/routing/scoring.rs:2161]: Not sure I understand why this is the lower value. Also, does this test exercise the right code path even prior to this change? Seems like it won't hit the log approximation because `amount_msat` is `u64::max_value()`.

File: lightning/src/routing/scoring.rs [hunk 6]
```diff
@@ -608,17 +626,12 @@ impl<L: Deref<Target = u64>, T: Time, U: Deref<Target = T>> DirectedChannelLiqui
...
-				u64::max_value()
-			} else {
-				// Equivalent to hitting the else clause below with the amount equal to the
-				// effective capacity and without any certainty on the liquidity upper bound.
-				let negative_log10_times_2048 = NEGATIVE_LOG10_UPPER_BOUND * 2048;
-				self.combined_penalty_msat(amount_msat, negative_log10_times_2048, params)
-			}
+			// Equivalent to hitting the else clause below with the amount equal to the effective
+			// capacity and without any certainty on the liquidity upper bound, plus the
+			// impossibility penalty.
```
Comment (jkczyz) [inline lightning/src/routing/scoring.rs:631]: This comment needs to be updated now since it's not only when equal to the effective capacity. Seems like the earlier change that added this now removed logic is what caused `calculates_log10_without_overflowing_u64_max_value` to not exercise the correct code path as mentioned earlier on that test (i.e., it doesn't hit the `negative_log10_times_2048` case below.

Comment (jkczyz) [reply lightning/src/routing/scoring.rs:631]: Ah, yeah, you're right!

File: lightning/src/routing/scoring.rs [hunk 7]
```diff
@@ -608,17 +626,12 @@ impl<L: Deref<Target = u64>, T: Time, U: Deref<Target = T>> DirectedChannelLiqui
...
+			let negative_log10_times_2048 = NEGATIVE_LOG10_UPPER_BOUND * 2048;
+			self.combined_penalty_msat(amount_msat, negative_log10_times_2048, params)
+				.saturating_add(params.considered_impossible_penalty_msat)
```
Comment (jkczyz) [inline lightning/src/routing/scoring.rs:634]: Would it make sense to do the max of these two rather than adding? Is the idea that we want this to be `>=` anything given in the `else` clause?

**Review by jkczyz — COMMENTED** [review]
Largely looks good but one comment.

File: lightning/src/routing/scoring.rs (hunk 7 above)
Comment (jkczyz) [reply lightning/src/routing/scoring.rs:634]: > Right, sure, I just meant it'd be easy for a user to look at the field and think "okay, let me pick something a bit higher than the liquidity offset, forget to multiply by 2 or whatever, and end up with a penalty equal to the liquidity penalty, which seems wrong?

Plus base and amount penalty, FWIW.

> I dunno, I'm happy to mentally convert when we're debugging. Unless you feel strongly I'd suggest we leave it.

Sure we can leave it. Though one thing I just realized is that either way now the penalty will be variable across channels depending on the amount. Maybe less so when using `max` but maybe that's an argument in favor of adding. That way if left to choose only channels exceeding the maximum liquidity, we'd prefer ones that would otherwise be penalized less.

**Review by jkczyz — APPROVED** [review]

File: lightning/src/routing/scoring.rs [hunk 8]
```diff
@@ -392,6 +392,22 @@ pub struct ProbabilisticScoringParameters {
 	///
 	/// Default value: 250 msat
 	pub anti_probing_penalty_msat: u64,
+
+	/// This penalty is applied when the amount we're attempting to send over a channel exceeds our
+	/// current estimate of the channel's available liquidity.
+	///
+	/// Note that in this case the [`liquidity_penalty_multiplier_msat`] and
+	/// [`amount_penalty_multiplier_msat`]-based penalties are still included in the overall
+	/// penalty.
```
Comment (jkczyz) [inline lightning/src/routing/scoring.rs:401]: nit: `base_penalty_msat` is also included.

**Review by jkczyz — APPROVED** [review]

**Review by jkczyz — APPROVED** [review]

**Review by jkczyz — APPROVED** [review]

**Review by tnull — APPROVED** [review]

**Comment by jkczyz** [comment]
> Oops, right, sorry, rewrote that commit message without changes to the diff, added a note that it this does have the drawback of potentially retrying different parts along the same path, but hopefully the scorer doesn't let that happen unless the payment is gonna fail anyway.

Yeah, same across payments, but as you said hopefully the scorer will learn quickly enough.

**Review by jkczyz — APPROVED** [review]

**Review by jkczyz — APPROVED** [review]

**Review by tnull — APPROVED** [review]
